version: '3.1'
services:
  db:
    command: mysqld --log-output=NONE --slow-query-log=0 --general-log=0 --innodb-flush-log-at-trx-commit=2 --innodb-log-buffer-size=3M --innodb-buffer-pool-size=180M
    image: mariadb:10.4
    tmpfs: /var/lib/mysql
    #volumes:
    #  - ../../.docker/db/:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: secure_root_password
      MYSQL_USER: oscar
      MYSQL_PASSWORD: oscar
      MYSQL_DATABASE: oscar_test
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 3306:3306

