
// files extensions that can be uploaded as message attachment
export const AllowedAttachmentTypes = [
	"image/*",
	"video/*",
	"audio/*",
	"file/*",
	".txt",
	".csv",
	".rtf",
	".rtx",
	".jpg", ".jpeg", ".jpe",
	".jp2",
	".png",
	".gif",
	".bmp",
	".svg",
	".tiff",
	".pdf",
	".doc", ".docx",
	".xls", ".xlsx",
	".wav",
	".mp3",
];

// mime types that can be uploaded as message attachment
export const AllowedAttachmentMimeTypes = [
	"text/plain",
	"text/csv",
	"text/rtf",
	"text/richtext",
	"image/jpeg",
	"image/jp2",
	"image/x-citrix-jpeg",
	"image/png",
	"image/x-png",
	"image/x-citrix-png",
	"image/gif",
	"image/bmp",
	"image/tiff",
	"image/svg+xml",
	"application/pdf",
	"application/msword",
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	"application/zip",
	"application/vnd.ms-excel",
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	"audio/x-wav",
	"audio/mpeg",
]