//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.23 at 02:21:20 PM PDT 
//


package org.oscarehr.common.xml.cds.v5_0.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for immunizationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="immunizationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;maxLength value="20"/>
 *     &lt;enumeration value="BCG"/>
 *     &lt;enumeration value="Chol-O"/>
 *     &lt;enumeration value="Chol-Ecol-O"/>
 *     &lt;enumeration value="CholEcol"/>
 *     &lt;enumeration value="DTaP"/>
 *     &lt;enumeration value="DTaP-IPV"/>
 *     &lt;enumeration value="DTaP-IPV-Hib"/>
 *     &lt;enumeration value="DTaP-IPV-Hib-HB"/>
 *     &lt;enumeration value="DTaP-IPV-HB"/>
 *     &lt;enumeration value="DTaP-Hib"/>
 *     &lt;enumeration value="DT-IPV"/>
 *     &lt;enumeration value="HA"/>
 *     &lt;enumeration value="HAHB"/>
 *     &lt;enumeration value="HA-Typh-I"/>
 *     &lt;enumeration value="HB"/>
 *     &lt;enumeration value="HBTmf"/>
 *     &lt;enumeration value="Hib"/>
 *     &lt;enumeration value="Inf"/>
 *     &lt;enumeration value="IPV"/>
 *     &lt;enumeration value="JE"/>
 *     &lt;enumeration value="Men"/>
 *     &lt;enumeration value="Men B"/>
 *     &lt;enumeration value="Men-C"/>
 *     &lt;enumeration value="Men-P-AC"/>
 *     &lt;enumeration value="Men-P-ACWY"/>
 *     &lt;enumeration value="MMR"/>
 *     &lt;enumeration value="MR"/>
 *     &lt;enumeration value="Pneu"/>
 *     &lt;enumeration value="Pneu-C-7"/>
 *     &lt;enumeration value="Pneu-P-23"/>
 *     &lt;enumeration value="Rab"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="Td"/>
 *     &lt;enumeration value="Tdap"/>
 *     &lt;enumeration value="TdapIPV"/>
 *     &lt;enumeration value="Td-IPV"/>
 *     &lt;enumeration value="TBE"/>
 *     &lt;enumeration value="Typh"/>
 *     &lt;enumeration value="Typh (HA)"/>
 *     &lt;enumeration value="Typh-I"/>
 *     &lt;enumeration value="Typh-O"/>
 *     &lt;enumeration value="Var"/>
 *     &lt;enumeration value="YF"/>
 *     &lt;enumeration value="HPV"/>
 *     &lt;enumeration value="MMR-Var"/>
 *     &lt;enumeration value="ROT"/>
 *     &lt;enumeration value="Zos"/>
 *     &lt;enumeration value="BAtx"/>
 *     &lt;enumeration value="CMVIg"/>
 *     &lt;enumeration value="DAtx"/>
 *     &lt;enumeration value="HBIg"/>
 *     &lt;enumeration value="Ig"/>
 *     &lt;enumeration value="RabIg"/>
 *     &lt;enumeration value="RSVAb"/>
 *     &lt;enumeration value="RSVIg"/>
 *     &lt;enumeration value="TIg"/>
 *     &lt;enumeration value="VarIg"/>
 *     &lt;enumeration value="VIG"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "immunizationType")
@XmlEnum
public enum ImmunizationType {

    BCG("BCG"),
    @XmlEnumValue("Chol-O")
    CHOL_O("Chol-O"),
    @XmlEnumValue("Chol-Ecol-O")
    CHOL_ECOL_O("Chol-Ecol-O"),
    @XmlEnumValue("CholEcol")
    CHOL_ECOL("CholEcol"),
    @XmlEnumValue("DTaP")
    D_TA_P("DTaP"),
    @XmlEnumValue("DTaP-IPV")
    D_TA_P_IPV("DTaP-IPV"),
    @XmlEnumValue("DTaP-IPV-Hib")
    D_TA_P_IPV_HIB("DTaP-IPV-Hib"),
    @XmlEnumValue("DTaP-IPV-Hib-HB")
    D_TA_P_IPV_HIB_HB("DTaP-IPV-Hib-HB"),
    @XmlEnumValue("DTaP-IPV-HB")
    D_TA_P_IPV_HB("DTaP-IPV-HB"),
    @XmlEnumValue("DTaP-Hib")
    D_TA_P_HIB("DTaP-Hib"),
    @XmlEnumValue("DT-IPV")
    DT_IPV("DT-IPV"),
    HA("HA"),
    HAHB("HAHB"),
    @XmlEnumValue("HA-Typh-I")
    HA_TYPH_I("HA-Typh-I"),
    HB("HB"),
    @XmlEnumValue("HBTmf")
    HB_TMF("HBTmf"),
    @XmlEnumValue("Hib")
    HIB("Hib"),
    @XmlEnumValue("Inf")
    INF("Inf"),
    IPV("IPV"),
    JE("JE"),
    @XmlEnumValue("Men")
    MEN("Men"),
    @XmlEnumValue("Men B")
    MEN_B("Men B"),
    @XmlEnumValue("Men-C")
    MEN_C("Men-C"),
    @XmlEnumValue("Men-P-AC")
    MEN_P_AC("Men-P-AC"),
    @XmlEnumValue("Men-P-ACWY")
    MEN_P_ACWY("Men-P-ACWY"),
    MMR("MMR"),
    MR("MR"),
    @XmlEnumValue("Pneu")
    PNEU("Pneu"),
    @XmlEnumValue("Pneu-C-7")
    PNEU_C_7("Pneu-C-7"),
    @XmlEnumValue("Pneu-P-23")
    PNEU_P_23("Pneu-P-23"),
    @XmlEnumValue("Rab")
    RAB("Rab"),
    T("T"),
    @XmlEnumValue("Td")
    TD("Td"),
    @XmlEnumValue("Tdap")
    TDAP("Tdap"),
    @XmlEnumValue("TdapIPV")
    TDAP_IPV("TdapIPV"),
    @XmlEnumValue("Td-IPV")
    TD_IPV("Td-IPV"),
    TBE("TBE"),
    @XmlEnumValue("Typh")
    TYPH("Typh"),
    @XmlEnumValue("Typh (HA)")
    TYPH_HA("Typh (HA)"),
    @XmlEnumValue("Typh-I")
    TYPH_I("Typh-I"),
    @XmlEnumValue("Typh-O")
    TYPH_O("Typh-O"),
    @XmlEnumValue("Var")
    VAR("Var"),
    YF("YF"),
    HPV("HPV"),
    @XmlEnumValue("MMR-Var")
    MMR_VAR("MMR-Var"),
    ROT("ROT"),
    @XmlEnumValue("Zos")
    ZOS("Zos"),
    @XmlEnumValue("BAtx")
    B_ATX("BAtx"),
    @XmlEnumValue("CMVIg")
    CMV_IG("CMVIg"),
    @XmlEnumValue("DAtx")
    D_ATX("DAtx"),
    @XmlEnumValue("HBIg")
    HB_IG("HBIg"),
    @XmlEnumValue("Ig")
    IG("Ig"),
    @XmlEnumValue("RabIg")
    RAB_IG("RabIg"),
    @XmlEnumValue("RSVAb")
    RSV_AB("RSVAb"),
    @XmlEnumValue("RSVIg")
    RSV_IG("RSVIg"),
    @XmlEnumValue("TIg")
    T_IG("TIg"),
    @XmlEnumValue("VarIg")
    VAR_IG("VarIg"),
    VIG("VIG");
    private final String value;

    ImmunizationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ImmunizationType fromValue(String v) {
        for (ImmunizationType c: ImmunizationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
