//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.20 at 02:31:59 PM PDT 
//


package org.oscarehr.common.xml.cds.v5_0.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FirstName">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Part" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PartType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LastName">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Part" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PartType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="namePurpose" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "firstName",
    "lastName"
})
@XmlRootElement(name = "LegalName", namespace = "cds_dt")
public class LegalName {

    @XmlElement(name = "FirstName", namespace = "cds_dt", required = true)
    protected LegalName.FirstName firstName;
    @XmlElement(name = "LastName", namespace = "cds_dt", required = true)
    protected LegalName.LastName lastName;
    @XmlAttribute(name = "namePurpose", required = true)
    protected String namePurpose;

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link LegalName.FirstName }
     *     
     */
    public LegalName.FirstName getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalName.FirstName }
     *     
     */
    public void setFirstName(LegalName.FirstName value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link LegalName.LastName }
     *     
     */
    public LegalName.LastName getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalName.LastName }
     *     
     */
    public void setLastName(LegalName.LastName value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the namePurpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamePurpose() {
        return namePurpose;
    }

    /**
     * Sets the value of the namePurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamePurpose(String value) {
        this.namePurpose = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Part" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PartType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "part",
        "partType"
    })
    public static class FirstName {

        @XmlElement(name = "Part", namespace = "cds_dt", required = true)
        protected String part;
        @XmlElement(name = "PartType", namespace = "cds_dt", required = true)
        protected String partType;

        /**
         * Gets the value of the part property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPart() {
            return part;
        }

        /**
         * Sets the value of the part property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPart(String value) {
            this.part = value;
        }

        /**
         * Gets the value of the partType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPartType() {
            return partType;
        }

        /**
         * Sets the value of the partType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPartType(String value) {
            this.partType = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Part" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PartType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "part",
        "partType"
    })
    public static class LastName {

        @XmlElement(name = "Part", namespace = "cds_dt", required = true)
        protected String part;
        @XmlElement(name = "PartType", namespace = "cds_dt", required = true)
        protected String partType;

        /**
         * Gets the value of the part property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPart() {
            return part;
        }

        /**
         * Sets the value of the part property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPart(String value) {
            this.part = value;
        }

        /**
         * Gets the value of the partType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPartType() {
            return partType;
        }

        /**
         * Sets the value of the partType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPartType(String value) {
            this.partType = value;
        }

    }

}
