//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.22 at 05:00:32 PM PDT 
//


package org.oscarehr.common.xml.cds.v5_0.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.oscarehr.common.xml.cds.v5_0.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LastName_QNAME = new QName("cds_dt", "LastName");
    private final static QName _ProvinceCode_QNAME = new QName("cds_dt", "ProvinceCode");
    private final static QName _PurposeAsPlainText_QNAME = new QName("cds_dt", "PurposeAsPlainText");
    private final static QName _MiddleName_QNAME = new QName("cds_dt", "MiddleName");
    private final static QName _PhoneNumber_QNAME = new QName("cds_dt", "phoneNumber");
    private final static QName _ExpiryDate_QNAME = new QName("cds_dt", "ExpiryDate");
    private final static QName _FirstName_QNAME = new QName("cds_dt", "FirstName");
    private final static QName _Version_QNAME = new QName("cds_dt", "Version");
    private final static QName _PurposeAsEnum_QNAME = new QName("cds_dt", "PurposeAsEnum");
    private final static QName _Number_QNAME = new QName("cds_dt", "Number");
    private final static QName _FullDate_QNAME = new QName("cds_dt", "FullDate");
    private final static QName _PatientRecordAppointmentsAppointmentNotes_QNAME = new QName("", "AppointmentNotes");
    private final static QName _PatientRecordAppointmentsAppointmentTime_QNAME = new QName("", "AppointmentTime");
    private final static QName _PatientRecordAppointmentsDuration_QNAME = new QName("", "Duration");
    private final static QName _PatientRecordAppointmentsAppointmentStatus_QNAME = new QName("", "AppointmentStatus");
    private final static QName _PatientRecordAppointmentsAppointmentDate_QNAME = new QName("", "AppointmentDate");
    private final static QName _PatientRecordAppointmentsAppointmentPurpose_QNAME = new QName("", "AppointmentPurpose");
    private final static QName _PatientRecordAppointmentsProvider_QNAME = new QName("", "Provider");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.oscarehr.common.xml.cds.v5_0.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PatientRecord }
     * 
     */
    public PatientRecord createPatientRecord() {
        return new PatientRecord();
    }

    /**
     * Create an instance of {@link LegalName }
     * 
     */
    public LegalName createLegalName() {
        return new LegalName();
    }

    /**
     * Create an instance of {@link PatientRecord.Appointments }
     * 
     */
    public PatientRecord.Appointments createPatientRecordAppointments() {
        return new PatientRecord.Appointments();
    }

    /**
     * Create an instance of {@link PatientRecord.Appointments.Provider }
     * 
     */
    public PatientRecord.Appointments.Provider createPatientRecordAppointmentsProvider() {
        return new PatientRecord.Appointments.Provider();
    }

    /**
     * Create an instance of {@link PatientRecord.Demographics }
     * 
     */
    public PatientRecord.Demographics createPatientRecordDemographics() {
        return new PatientRecord.Demographics();
    }

    /**
     * Create an instance of {@link PatientRecord.Demographics.PrimaryPhysician }
     * 
     */
    public PatientRecord.Demographics.PrimaryPhysician createPatientRecordDemographicsPrimaryPhysician() {
        return new PatientRecord.Demographics.PrimaryPhysician();
    }

    /**
     * Create an instance of {@link PatientRecord.Demographics.Contact }
     * 
     */
    public PatientRecord.Demographics.Contact createPatientRecordDemographicsContact() {
        return new PatientRecord.Demographics.Contact();
    }

    /**
     * Create an instance of {@link PatientRecord.PersonalHistory }
     * 
     */
    public PatientRecord.PersonalHistory createPatientRecordPersonalHistory() {
        return new PatientRecord.PersonalHistory();
    }

    /**
     * Create an instance of {@link PatientRecord.FamilyHistory }
     * 
     */
    public PatientRecord.FamilyHistory createPatientRecordFamilyHistory() {
        return new PatientRecord.FamilyHistory();
    }

    /**
     * Create an instance of {@link PatientRecord.PastHealth }
     * 
     */
    public PatientRecord.PastHealth createPatientRecordPastHealth() {
        return new PatientRecord.PastHealth();
    }

    /**
     * Create an instance of {@link PatientRecord.ProblemList }
     * 
     */
    public PatientRecord.ProblemList createPatientRecordProblemList() {
        return new PatientRecord.ProblemList();
    }

    /**
     * Create an instance of {@link PatientRecord.RiskFactors }
     * 
     */
    public PatientRecord.RiskFactors createPatientRecordRiskFactors() {
        return new PatientRecord.RiskFactors();
    }

    /**
     * Create an instance of {@link PatientRecord.AllergiesAndAdverseReactions }
     * 
     */
    public PatientRecord.AllergiesAndAdverseReactions createPatientRecordAllergiesAndAdverseReactions() {
        return new PatientRecord.AllergiesAndAdverseReactions();
    }

    /**
     * Create an instance of {@link PatientRecord.MedicationsAndTreatments }
     * 
     */
    public PatientRecord.MedicationsAndTreatments createPatientRecordMedicationsAndTreatments() {
        return new PatientRecord.MedicationsAndTreatments();
    }

    /**
     * Create an instance of {@link PatientRecord.Immunizations }
     * 
     */
    public PatientRecord.Immunizations createPatientRecordImmunizations() {
        return new PatientRecord.Immunizations();
    }

    /**
     * Create an instance of {@link PatientRecord.LaboratoryResults }
     * 
     */
    public PatientRecord.LaboratoryResults createPatientRecordLaboratoryResults() {
        return new PatientRecord.LaboratoryResults();
    }

    /**
     * Create an instance of {@link PatientRecord.ClinicalNotes }
     * 
     */
    public PatientRecord.ClinicalNotes createPatientRecordClinicalNotes() {
        return new PatientRecord.ClinicalNotes();
    }

    /**
     * Create an instance of {@link PatientRecord.Reports }
     * 
     */
    public PatientRecord.Reports createPatientRecordReports() {
        return new PatientRecord.Reports();
    }

    /**
     * Create an instance of {@link PatientRecord.CareElements }
     * 
     */
    public PatientRecord.CareElements createPatientRecordCareElements() {
        return new PatientRecord.CareElements();
    }

    /**
     * Create an instance of {@link PatientRecord.AlertsAndSpecialNeeds }
     * 
     */
    public PatientRecord.AlertsAndSpecialNeeds createPatientRecordAlertsAndSpecialNeeds() {
        return new PatientRecord.AlertsAndSpecialNeeds();
    }

    /**
     * Create an instance of {@link PatientRecord.NewCategory }
     * 
     */
    public PatientRecord.NewCategory createPatientRecordNewCategory() {
        return new PatientRecord.NewCategory();
    }

    /**
     * Create an instance of {@link LegalName.FirstName }
     * 
     */
    public LegalName.FirstName createLegalNameFirstName() {
        return new LegalName.FirstName();
    }

    /**
     * Create an instance of {@link LegalName.LastName }
     * 
     */
    public LegalName.LastName createLegalNameLastName() {
        return new LegalName.LastName();
    }

    /**
     * Create an instance of {@link Structured }
     * 
     */
    public Structured createStructured() {
        return new Structured();
    }

    /**
     * Create an instance of {@link PatientRecord.Appointments.AppointmentDate }
     * 
     */
    public PatientRecord.Appointments.AppointmentDate createPatientRecordAppointmentsAppointmentDate() {
        return new PatientRecord.Appointments.AppointmentDate();
    }

    /**
     * Create an instance of {@link PatientRecord.Appointments.Provider.Name }
     * 
     */
    public PatientRecord.Appointments.Provider.Name createPatientRecordAppointmentsProviderName() {
        return new PatientRecord.Appointments.Provider.Name();
    }

    /**
     * Create an instance of {@link PatientRecord.Demographics.Names }
     * 
     */
    public PatientRecord.Demographics.Names createPatientRecordDemographicsNames() {
        return new PatientRecord.Demographics.Names();
    }

    /**
     * Create an instance of {@link PatientRecord.Demographics.HealthCard }
     * 
     */
    public PatientRecord.Demographics.HealthCard createPatientRecordDemographicsHealthCard() {
        return new PatientRecord.Demographics.HealthCard();
    }

    /**
     * Create an instance of {@link PatientRecord.Demographics.Address }
     * 
     */
    public PatientRecord.Demographics.Address createPatientRecordDemographicsAddress() {
        return new PatientRecord.Demographics.Address();
    }

    /**
     * Create an instance of {@link PatientRecord.Demographics.PhoneNumber }
     * 
     */
    public PatientRecord.Demographics.PhoneNumber createPatientRecordDemographicsPhoneNumber() {
        return new PatientRecord.Demographics.PhoneNumber();
    }

    /**
     * Create an instance of {@link PatientRecord.Demographics.Enrolment }
     * 
     */
    public PatientRecord.Demographics.Enrolment createPatientRecordDemographicsEnrolment() {
        return new PatientRecord.Demographics.Enrolment();
    }

    /**
     * Create an instance of {@link PatientRecord.Demographics.PersonStatusCode }
     * 
     */
    public PatientRecord.Demographics.PersonStatusCode createPatientRecordDemographicsPersonStatusCode() {
        return new PatientRecord.Demographics.PersonStatusCode();
    }

    /**
     * Create an instance of {@link PatientRecord.Demographics.PrimaryPhysician.Name }
     * 
     */
    public PatientRecord.Demographics.PrimaryPhysician.Name createPatientRecordDemographicsPrimaryPhysicianName() {
        return new PatientRecord.Demographics.PrimaryPhysician.Name();
    }

    /**
     * Create an instance of {@link PatientRecord.Demographics.Contact.ContactPurpose }
     * 
     */
    public PatientRecord.Demographics.Contact.ContactPurpose createPatientRecordDemographicsContactContactPurpose() {
        return new PatientRecord.Demographics.Contact.ContactPurpose();
    }

    /**
     * Create an instance of {@link PatientRecord.Demographics.Contact.Name }
     * 
     */
    public PatientRecord.Demographics.Contact.Name createPatientRecordDemographicsContactName() {
        return new PatientRecord.Demographics.Contact.Name();
    }

    /**
     * Create an instance of {@link PatientRecord.Demographics.Contact.PhoneNumber }
     * 
     */
    public PatientRecord.Demographics.Contact.PhoneNumber createPatientRecordDemographicsContactPhoneNumber() {
        return new PatientRecord.Demographics.Contact.PhoneNumber();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "LastName")
    public JAXBElement<String> createLastName(String value) {
        return new JAXBElement<String>(_LastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "ProvinceCode")
    public JAXBElement<String> createProvinceCode(String value) {
        return new JAXBElement<String>(_ProvinceCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "PurposeAsPlainText")
    public JAXBElement<String> createPurposeAsPlainText(String value) {
        return new JAXBElement<String>(_PurposeAsPlainText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "MiddleName")
    public JAXBElement<String> createMiddleName(String value) {
        return new JAXBElement<String>(_MiddleName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "phoneNumber")
    public JAXBElement<String> createPhoneNumber(String value) {
        return new JAXBElement<String>(_PhoneNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "ExpiryDate")
    public JAXBElement<XMLGregorianCalendar> createExpiryDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ExpiryDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "FirstName")
    public JAXBElement<String> createFirstName(String value) {
        return new JAXBElement<String>(_FirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "Version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "PurposeAsEnum")
    public JAXBElement<String> createPurposeAsEnum(String value) {
        return new JAXBElement<String>(_PurposeAsEnum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "Number")
    public JAXBElement<String> createNumber(String value) {
        return new JAXBElement<String>(_Number_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "FullDate")
    public JAXBElement<XMLGregorianCalendar> createFullDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_FullDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AppointmentNotes", scope = PatientRecord.Appointments.class)
    public JAXBElement<String> createPatientRecordAppointmentsAppointmentNotes(String value) {
        return new JAXBElement<String>(_PatientRecordAppointmentsAppointmentNotes_QNAME, String.class, PatientRecord.Appointments.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AppointmentTime", scope = PatientRecord.Appointments.class)
    public JAXBElement<XMLGregorianCalendar> createPatientRecordAppointmentsAppointmentTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PatientRecordAppointmentsAppointmentTime_QNAME, XMLGregorianCalendar.class, PatientRecord.Appointments.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Duration", scope = PatientRecord.Appointments.class)
    public JAXBElement<Short> createPatientRecordAppointmentsDuration(Short value) {
        return new JAXBElement<Short>(_PatientRecordAppointmentsDuration_QNAME, Short.class, PatientRecord.Appointments.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AppointmentStatus", scope = PatientRecord.Appointments.class)
    public JAXBElement<String> createPatientRecordAppointmentsAppointmentStatus(String value) {
        return new JAXBElement<String>(_PatientRecordAppointmentsAppointmentStatus_QNAME, String.class, PatientRecord.Appointments.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatientRecord.Appointments.AppointmentDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AppointmentDate", scope = PatientRecord.Appointments.class)
    public JAXBElement<PatientRecord.Appointments.AppointmentDate> createPatientRecordAppointmentsAppointmentDate(PatientRecord.Appointments.AppointmentDate value) {
        return new JAXBElement<PatientRecord.Appointments.AppointmentDate>(_PatientRecordAppointmentsAppointmentDate_QNAME, PatientRecord.Appointments.AppointmentDate.class, PatientRecord.Appointments.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AppointmentPurpose", scope = PatientRecord.Appointments.class)
    public JAXBElement<String> createPatientRecordAppointmentsAppointmentPurpose(String value) {
        return new JAXBElement<String>(_PatientRecordAppointmentsAppointmentPurpose_QNAME, String.class, PatientRecord.Appointments.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatientRecord.Appointments.Provider }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Provider", scope = PatientRecord.Appointments.class)
    public JAXBElement<PatientRecord.Appointments.Provider> createPatientRecordAppointmentsProvider(PatientRecord.Appointments.Provider value) {
        return new JAXBElement<PatientRecord.Appointments.Provider>(_PatientRecordAppointmentsProvider_QNAME, PatientRecord.Appointments.Provider.class, PatientRecord.Appointments.class, value);
    }

}
