//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.20 at 02:31:59 PM PDT 
//


package org.oscarehr.common.xml.cds.v5_0.model;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.oscarehr.common.xml.cds.v5_0.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProvinceCode_QNAME = new QName("cds_dt", "ProvinceCode");
    private final static QName _LastName_QNAME = new QName("cds_dt", "LastName");
    private final static QName _PhoneNumber_QNAME = new QName("cds_dt", "phoneNumber");
    private final static QName _FirstName_QNAME = new QName("cds_dt", "FirstName");
    private final static QName _Number_QNAME = new QName("cds_dt", "Number");
    private final static QName _FullDate_QNAME = new QName("cds_dt", "FullDate");
    private final static QName _OmdCdsPatientRecordAppointmentsAppointmentNotes_QNAME = new QName("cds", "AppointmentNotes");
    private final static QName _OmdCdsPatientRecordAppointmentsAppointmentTime_QNAME = new QName("cds", "AppointmentTime");
    private final static QName _OmdCdsPatientRecordAppointmentsAppointmentStatus_QNAME = new QName("cds", "AppointmentStatus");
    private final static QName _OmdCdsPatientRecordAppointmentsDuration_QNAME = new QName("cds", "Duration");
    private final static QName _OmdCdsPatientRecordAppointmentsProvider_QNAME = new QName("cds", "Provider");
    private final static QName _OmdCdsPatientRecordAppointmentsAppointmentDate_QNAME = new QName("cds", "AppointmentDate");
    private final static QName _OmdCdsPatientRecordAppointmentsAppointmentPurpose_QNAME = new QName("cds", "AppointmentPurpose");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.oscarehr.common.xml.cds.v5_0.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OmdCds }
     * 
     */
    public OmdCds createOmdCds() {
        return new OmdCds();
    }

    /**
     * Create an instance of {@link LegalName }
     * 
     */
    public LegalName createLegalName() {
        return new LegalName();
    }

    /**
     * Create an instance of {@link OmdCds.PatientRecord }
     * 
     */
    public OmdCds.PatientRecord createOmdCdsPatientRecord() {
        return new OmdCds.PatientRecord();
    }

    /**
     * Create an instance of {@link OmdCds.PatientRecord.Appointments }
     * 
     */
    public OmdCds.PatientRecord.Appointments createOmdCdsPatientRecordAppointments() {
        return new OmdCds.PatientRecord.Appointments();
    }

    /**
     * Create an instance of {@link OmdCds.PatientRecord.Appointments.Provider }
     * 
     */
    public OmdCds.PatientRecord.Appointments.Provider createOmdCdsPatientRecordAppointmentsProvider() {
        return new OmdCds.PatientRecord.Appointments.Provider();
    }

    /**
     * Create an instance of {@link OmdCds.PatientRecord.Demographics }
     * 
     */
    public OmdCds.PatientRecord.Demographics createOmdCdsPatientRecordDemographics() {
        return new OmdCds.PatientRecord.Demographics();
    }

    /**
     * Create an instance of {@link OmdCds.PatientRecord.Demographics.PrimaryPhysician }
     * 
     */
    public OmdCds.PatientRecord.Demographics.PrimaryPhysician createOmdCdsPatientRecordDemographicsPrimaryPhysician() {
        return new OmdCds.PatientRecord.Demographics.PrimaryPhysician();
    }

    /**
     * Create an instance of {@link LegalName.FirstName }
     * 
     */
    public LegalName.FirstName createLegalNameFirstName() {
        return new LegalName.FirstName();
    }

    /**
     * Create an instance of {@link LegalName.LastName }
     * 
     */
    public LegalName.LastName createLegalNameLastName() {
        return new LegalName.LastName();
    }

    /**
     * Create an instance of {@link OmdCds.PatientRecord.Appointments.AppointmentDate }
     * 
     */
    public OmdCds.PatientRecord.Appointments.AppointmentDate createOmdCdsPatientRecordAppointmentsAppointmentDate() {
        return new OmdCds.PatientRecord.Appointments.AppointmentDate();
    }

    /**
     * Create an instance of {@link OmdCds.PatientRecord.Appointments.Provider.Name }
     * 
     */
    public OmdCds.PatientRecord.Appointments.Provider.Name createOmdCdsPatientRecordAppointmentsProviderName() {
        return new OmdCds.PatientRecord.Appointments.Provider.Name();
    }

    /**
     * Create an instance of {@link OmdCds.PatientRecord.Demographics.Names }
     * 
     */
    public OmdCds.PatientRecord.Demographics.Names createOmdCdsPatientRecordDemographicsNames() {
        return new OmdCds.PatientRecord.Demographics.Names();
    }

    /**
     * Create an instance of {@link OmdCds.PatientRecord.Demographics.HealthCard }
     * 
     */
    public OmdCds.PatientRecord.Demographics.HealthCard createOmdCdsPatientRecordDemographicsHealthCard() {
        return new OmdCds.PatientRecord.Demographics.HealthCard();
    }

    /**
     * Create an instance of {@link OmdCds.PatientRecord.Demographics.PhoneNumber }
     * 
     */
    public OmdCds.PatientRecord.Demographics.PhoneNumber createOmdCdsPatientRecordDemographicsPhoneNumber() {
        return new OmdCds.PatientRecord.Demographics.PhoneNumber();
    }

    /**
     * Create an instance of {@link OmdCds.PatientRecord.Demographics.Enrolment }
     * 
     */
    public OmdCds.PatientRecord.Demographics.Enrolment createOmdCdsPatientRecordDemographicsEnrolment() {
        return new OmdCds.PatientRecord.Demographics.Enrolment();
    }

    /**
     * Create an instance of {@link OmdCds.PatientRecord.Demographics.PersonStatusCode }
     * 
     */
    public OmdCds.PatientRecord.Demographics.PersonStatusCode createOmdCdsPatientRecordDemographicsPersonStatusCode() {
        return new OmdCds.PatientRecord.Demographics.PersonStatusCode();
    }

    /**
     * Create an instance of {@link OmdCds.PatientRecord.Demographics.PrimaryPhysician.Name }
     * 
     */
    public OmdCds.PatientRecord.Demographics.PrimaryPhysician.Name createOmdCdsPatientRecordDemographicsPrimaryPhysicianName() {
        return new OmdCds.PatientRecord.Demographics.PrimaryPhysician.Name();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "ProvinceCode")
    public JAXBElement<String> createProvinceCode(String value) {
        return new JAXBElement<String>(_ProvinceCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "LastName")
    public JAXBElement<String> createLastName(String value) {
        return new JAXBElement<String>(_LastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "phoneNumber")
    public JAXBElement<BigInteger> createPhoneNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_PhoneNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "FirstName")
    public JAXBElement<String> createFirstName(String value) {
        return new JAXBElement<String>(_FirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "Number")
    public JAXBElement<BigInteger> createNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_Number_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds_dt", name = "FullDate")
    public JAXBElement<XMLGregorianCalendar> createFullDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_FullDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds", name = "AppointmentNotes", scope = OmdCds.PatientRecord.Appointments.class)
    public JAXBElement<String> createOmdCdsPatientRecordAppointmentsAppointmentNotes(String value) {
        return new JAXBElement<String>(_OmdCdsPatientRecordAppointmentsAppointmentNotes_QNAME, String.class, OmdCds.PatientRecord.Appointments.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds", name = "AppointmentTime", scope = OmdCds.PatientRecord.Appointments.class)
    public JAXBElement<XMLGregorianCalendar> createOmdCdsPatientRecordAppointmentsAppointmentTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_OmdCdsPatientRecordAppointmentsAppointmentTime_QNAME, XMLGregorianCalendar.class, OmdCds.PatientRecord.Appointments.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds", name = "AppointmentStatus", scope = OmdCds.PatientRecord.Appointments.class)
    public JAXBElement<String> createOmdCdsPatientRecordAppointmentsAppointmentStatus(String value) {
        return new JAXBElement<String>(_OmdCdsPatientRecordAppointmentsAppointmentStatus_QNAME, String.class, OmdCds.PatientRecord.Appointments.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds", name = "Duration", scope = OmdCds.PatientRecord.Appointments.class)
    public JAXBElement<Short> createOmdCdsPatientRecordAppointmentsDuration(Short value) {
        return new JAXBElement<Short>(_OmdCdsPatientRecordAppointmentsDuration_QNAME, Short.class, OmdCds.PatientRecord.Appointments.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OmdCds.PatientRecord.Appointments.Provider }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds", name = "Provider", scope = OmdCds.PatientRecord.Appointments.class)
    public JAXBElement<OmdCds.PatientRecord.Appointments.Provider> createOmdCdsPatientRecordAppointmentsProvider(OmdCds.PatientRecord.Appointments.Provider value) {
        return new JAXBElement<OmdCds.PatientRecord.Appointments.Provider>(_OmdCdsPatientRecordAppointmentsProvider_QNAME, OmdCds.PatientRecord.Appointments.Provider.class, OmdCds.PatientRecord.Appointments.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OmdCds.PatientRecord.Appointments.AppointmentDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds", name = "AppointmentDate", scope = OmdCds.PatientRecord.Appointments.class)
    public JAXBElement<OmdCds.PatientRecord.Appointments.AppointmentDate> createOmdCdsPatientRecordAppointmentsAppointmentDate(OmdCds.PatientRecord.Appointments.AppointmentDate value) {
        return new JAXBElement<OmdCds.PatientRecord.Appointments.AppointmentDate>(_OmdCdsPatientRecordAppointmentsAppointmentDate_QNAME, OmdCds.PatientRecord.Appointments.AppointmentDate.class, OmdCds.PatientRecord.Appointments.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "cds", name = "AppointmentPurpose", scope = OmdCds.PatientRecord.Appointments.class)
    public JAXBElement<String> createOmdCdsPatientRecordAppointmentsAppointmentPurpose(String value) {
        return new JAXBElement<String>(_OmdCdsPatientRecordAppointmentsAppointmentPurpose_QNAME, String.class, OmdCds.PatientRecord.Appointments.class, value);
    }

}
