//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.20 at 02:31:59 PM PDT 
//


package org.oscarehr.common.xml.cds.v5_0.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PatientRecord">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Demographics">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Names">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{cds_dt}LegalName"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="HealthCard">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{cds_dt}Number"/>
 *                                       &lt;element ref="{cds_dt}ProvinceCode"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="UniqueVendorIdSequence" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="PhoneNumber" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{cds_dt}phoneNumber"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="phoneNumberType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Enrolment">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="EnrollmentStatus" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="PrimaryPhysician">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="OHIPPhysicianId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Name">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element ref="{cds_dt}FirstName"/>
 *                                                 &lt;element ref="{cds_dt}LastName"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PersonStatusCode">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="PersonStatusAsEnum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="PersonStatusDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Appointments" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;choice maxOccurs="unbounded">
 *                               &lt;element name="AppointmentTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                               &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                               &lt;element name="AppointmentStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="AppointmentDate">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element ref="{cds_dt}FullDate"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="Provider">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="OHIPPhysicianId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         &lt;element name="Name">
 *                                           &lt;complexType>
 *                                             &lt;complexContent>
 *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                 &lt;sequence>
 *                                                   &lt;element ref="{cds_dt}FirstName"/>
 *                                                   &lt;element ref="{cds_dt}LastName"/>
 *                                                 &lt;/sequence>
 *                                               &lt;/restriction>
 *                                             &lt;/complexContent>
 *                                           &lt;/complexType>
 *                                         &lt;/element>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="AppointmentNotes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="AppointmentPurpose" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;/choice>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "patientRecord"
})
@XmlRootElement(name = "OmdCds")
public class OmdCds {

    @XmlElement(name = "PatientRecord", required = true)
    protected OmdCds.PatientRecord patientRecord;

    /**
     * Gets the value of the patientRecord property.
     * 
     * @return
     *     possible object is
     *     {@link OmdCds.PatientRecord }
     *     
     */
    public OmdCds.PatientRecord getPatientRecord() {
        return patientRecord;
    }

    /**
     * Sets the value of the patientRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link OmdCds.PatientRecord }
     *     
     */
    public void setPatientRecord(OmdCds.PatientRecord value) {
        this.patientRecord = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Demographics">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Names">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{cds_dt}LegalName"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="HealthCard">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{cds_dt}Number"/>
     *                             &lt;element ref="{cds_dt}ProvinceCode"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="UniqueVendorIdSequence" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                   &lt;element name="PhoneNumber" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{cds_dt}phoneNumber"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="phoneNumberType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Enrolment">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="EnrollmentStatus" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="PrimaryPhysician">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="OHIPPhysicianId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="Name">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element ref="{cds_dt}FirstName"/>
     *                                       &lt;element ref="{cds_dt}LastName"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PersonStatusCode">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="PersonStatusAsEnum" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="PersonStatusDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Appointments" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice maxOccurs="unbounded">
     *                     &lt;element name="AppointmentTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *                     &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                     &lt;element name="AppointmentStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                     &lt;element name="AppointmentDate">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element ref="{cds_dt}FullDate"/>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                     &lt;element name="Provider">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="OHIPPhysicianId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               &lt;element name="Name">
     *                                 &lt;complexType>
     *                                   &lt;complexContent>
     *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                       &lt;sequence>
     *                                         &lt;element ref="{cds_dt}FirstName"/>
     *                                         &lt;element ref="{cds_dt}LastName"/>
     *                                       &lt;/sequence>
     *                                     &lt;/restriction>
     *                                   &lt;/complexContent>
     *                                 &lt;/complexType>
     *                               &lt;/element>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                     &lt;element name="AppointmentNotes" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                     &lt;element name="AppointmentPurpose" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;/choice>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "demographics",
        "appointments"
    })
    public static class PatientRecord {

        @XmlElement(name = "Demographics", required = true)
        protected OmdCds.PatientRecord.Demographics demographics;
        @XmlElement(name = "Appointments", required = true)
        protected List<OmdCds.PatientRecord.Appointments> appointments;

        /**
         * Gets the value of the demographics property.
         * 
         * @return
         *     possible object is
         *     {@link OmdCds.PatientRecord.Demographics }
         *     
         */
        public OmdCds.PatientRecord.Demographics getDemographics() {
            return demographics;
        }

        /**
         * Sets the value of the demographics property.
         * 
         * @param value
         *     allowed object is
         *     {@link OmdCds.PatientRecord.Demographics }
         *     
         */
        public void setDemographics(OmdCds.PatientRecord.Demographics value) {
            this.demographics = value;
        }

        /**
         * Gets the value of the appointments property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the appointments property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAppointments().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OmdCds.PatientRecord.Appointments }
         * 
         * 
         */
        public List<OmdCds.PatientRecord.Appointments> getAppointments() {
            if (appointments == null) {
                appointments = new ArrayList<OmdCds.PatientRecord.Appointments>();
            }
            return this.appointments;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice maxOccurs="unbounded">
         *           &lt;element name="AppointmentTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
         *           &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *           &lt;element name="AppointmentStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *           &lt;element name="AppointmentDate">
         *             &lt;complexType>
         *               &lt;complexContent>
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   &lt;sequence>
         *                     &lt;element ref="{cds_dt}FullDate"/>
         *                   &lt;/sequence>
         *                 &lt;/restriction>
         *               &lt;/complexContent>
         *             &lt;/complexType>
         *           &lt;/element>
         *           &lt;element name="Provider">
         *             &lt;complexType>
         *               &lt;complexContent>
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   &lt;sequence>
         *                     &lt;element name="OHIPPhysicianId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                     &lt;element name="Name">
         *                       &lt;complexType>
         *                         &lt;complexContent>
         *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                             &lt;sequence>
         *                               &lt;element ref="{cds_dt}FirstName"/>
         *                               &lt;element ref="{cds_dt}LastName"/>
         *                             &lt;/sequence>
         *                           &lt;/restriction>
         *                         &lt;/complexContent>
         *                       &lt;/complexType>
         *                     &lt;/element>
         *                   &lt;/sequence>
         *                 &lt;/restriction>
         *               &lt;/complexContent>
         *             &lt;/complexType>
         *           &lt;/element>
         *           &lt;element name="AppointmentNotes" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *           &lt;element name="AppointmentPurpose" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;/choice>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "appointmentTimeOrDurationOrAppointmentStatus"
        })
        public static class Appointments {

            @XmlElementRefs({
                @XmlElementRef(name = "Duration", namespace = "cds", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Provider", namespace = "cds", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "AppointmentPurpose", namespace = "cds", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "AppointmentDate", namespace = "cds", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "AppointmentStatus", namespace = "cds", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "AppointmentNotes", namespace = "cds", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "AppointmentTime", namespace = "cds", type = JAXBElement.class, required = false)
            })
            protected List<JAXBElement<?>> appointmentTimeOrDurationOrAppointmentStatus;

            /**
             * Gets the value of the appointmentTimeOrDurationOrAppointmentStatus property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the appointmentTimeOrDurationOrAppointmentStatus property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAppointmentTimeOrDurationOrAppointmentStatus().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link Short }{@code >}
             * {@link JAXBElement }{@code <}{@link OmdCds.PatientRecord.Appointments.Provider }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link OmdCds.PatientRecord.Appointments.AppointmentDate }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
             * 
             * 
             */
            public List<JAXBElement<?>> getAppointmentTimeOrDurationOrAppointmentStatus() {
                if (appointmentTimeOrDurationOrAppointmentStatus == null) {
                    appointmentTimeOrDurationOrAppointmentStatus = new ArrayList<JAXBElement<?>>();
                }
                return this.appointmentTimeOrDurationOrAppointmentStatus;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{cds_dt}FullDate"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "fullDate"
            })
            public static class AppointmentDate {

                @XmlElement(name = "FullDate", namespace = "cds_dt", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar fullDate;

                /**
                 * Gets the value of the fullDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getFullDate() {
                    return fullDate;
                }

                /**
                 * Sets the value of the fullDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setFullDate(XMLGregorianCalendar value) {
                    this.fullDate = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="OHIPPhysicianId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="Name">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element ref="{cds_dt}FirstName"/>
             *                   &lt;element ref="{cds_dt}LastName"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "ohipPhysicianId",
                "name"
            })
            public static class Provider {

                @XmlElement(name = "OHIPPhysicianId", required = true)
                protected Object ohipPhysicianId;
                @XmlElement(name = "Name", required = true)
                protected OmdCds.PatientRecord.Appointments.Provider.Name name;

                /**
                 * Gets the value of the ohipPhysicianId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getOHIPPhysicianId() {
                    return ohipPhysicianId;
                }

                /**
                 * Sets the value of the ohipPhysicianId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setOHIPPhysicianId(Object value) {
                    this.ohipPhysicianId = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link OmdCds.PatientRecord.Appointments.Provider.Name }
                 *     
                 */
                public OmdCds.PatientRecord.Appointments.Provider.Name getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link OmdCds.PatientRecord.Appointments.Provider.Name }
                 *     
                 */
                public void setName(OmdCds.PatientRecord.Appointments.Provider.Name value) {
                    this.name = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element ref="{cds_dt}FirstName"/>
                 *         &lt;element ref="{cds_dt}LastName"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "firstName",
                    "lastName"
                })
                public static class Name {

                    @XmlElement(name = "FirstName", namespace = "cds_dt", required = true)
                    protected String firstName;
                    @XmlElement(name = "LastName", namespace = "cds_dt", required = true)
                    protected String lastName;

                    /**
                     * Gets the value of the firstName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFirstName() {
                        return firstName;
                    }

                    /**
                     * Sets the value of the firstName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFirstName(String value) {
                        this.firstName = value;
                    }

                    /**
                     * Gets the value of the lastName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getLastName() {
                        return lastName;
                    }

                    /**
                     * Sets the value of the lastName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setLastName(String value) {
                        this.lastName = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Names">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{cds_dt}LegalName"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="HealthCard">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{cds_dt}Number"/>
         *                   &lt;element ref="{cds_dt}ProvinceCode"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="UniqueVendorIdSequence" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *         &lt;element name="PhoneNumber" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{cds_dt}phoneNumber"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="phoneNumberType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Enrolment">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="EnrollmentStatus" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="PrimaryPhysician">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="OHIPPhysicianId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="Name">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element ref="{cds_dt}FirstName"/>
         *                             &lt;element ref="{cds_dt}LastName"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PersonStatusCode">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="PersonStatusAsEnum" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="PersonStatusDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "names",
            "dateOfBirth",
            "healthCard",
            "gender",
            "uniqueVendorIdSequence",
            "phoneNumber",
            "enrolment",
            "primaryPhysician",
            "email",
            "personStatusCode",
            "personStatusDate"
        })
        public static class Demographics {

            @XmlElement(name = "Names", required = true)
            protected OmdCds.PatientRecord.Demographics.Names names;
            @XmlElement(name = "DateOfBirth", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar dateOfBirth;
            @XmlElement(name = "HealthCard", required = true)
            protected OmdCds.PatientRecord.Demographics.HealthCard healthCard;
            @XmlElement(name = "Gender", required = true)
            protected String gender;
            @XmlElement(name = "UniqueVendorIdSequence")
            @XmlSchemaType(name = "unsignedByte")
            protected short uniqueVendorIdSequence;
            @XmlElement(name = "PhoneNumber", required = true)
            protected List<OmdCds.PatientRecord.Demographics.PhoneNumber> phoneNumber;
            @XmlElement(name = "Enrolment", required = true)
            protected OmdCds.PatientRecord.Demographics.Enrolment enrolment;
            @XmlElement(name = "PrimaryPhysician", required = true)
            protected OmdCds.PatientRecord.Demographics.PrimaryPhysician primaryPhysician;
            @XmlElement(name = "Email", required = true)
            protected String email;
            @XmlElement(name = "PersonStatusCode", required = true)
            protected OmdCds.PatientRecord.Demographics.PersonStatusCode personStatusCode;
            @XmlElement(name = "PersonStatusDate", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar personStatusDate;

            /**
             * Gets the value of the names property.
             * 
             * @return
             *     possible object is
             *     {@link OmdCds.PatientRecord.Demographics.Names }
             *     
             */
            public OmdCds.PatientRecord.Demographics.Names getNames() {
                return names;
            }

            /**
             * Sets the value of the names property.
             * 
             * @param value
             *     allowed object is
             *     {@link OmdCds.PatientRecord.Demographics.Names }
             *     
             */
            public void setNames(OmdCds.PatientRecord.Demographics.Names value) {
                this.names = value;
            }

            /**
             * Gets the value of the dateOfBirth property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDateOfBirth() {
                return dateOfBirth;
            }

            /**
             * Sets the value of the dateOfBirth property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDateOfBirth(XMLGregorianCalendar value) {
                this.dateOfBirth = value;
            }

            /**
             * Gets the value of the healthCard property.
             * 
             * @return
             *     possible object is
             *     {@link OmdCds.PatientRecord.Demographics.HealthCard }
             *     
             */
            public OmdCds.PatientRecord.Demographics.HealthCard getHealthCard() {
                return healthCard;
            }

            /**
             * Sets the value of the healthCard property.
             * 
             * @param value
             *     allowed object is
             *     {@link OmdCds.PatientRecord.Demographics.HealthCard }
             *     
             */
            public void setHealthCard(OmdCds.PatientRecord.Demographics.HealthCard value) {
                this.healthCard = value;
            }

            /**
             * Gets the value of the gender property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGender() {
                return gender;
            }

            /**
             * Sets the value of the gender property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGender(String value) {
                this.gender = value;
            }

            /**
             * Gets the value of the uniqueVendorIdSequence property.
             * 
             */
            public short getUniqueVendorIdSequence() {
                return uniqueVendorIdSequence;
            }

            /**
             * Sets the value of the uniqueVendorIdSequence property.
             * 
             */
            public void setUniqueVendorIdSequence(short value) {
                this.uniqueVendorIdSequence = value;
            }

            /**
             * Gets the value of the phoneNumber property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the phoneNumber property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPhoneNumber().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link OmdCds.PatientRecord.Demographics.PhoneNumber }
             * 
             * 
             */
            public List<OmdCds.PatientRecord.Demographics.PhoneNumber> getPhoneNumber() {
                if (phoneNumber == null) {
                    phoneNumber = new ArrayList<OmdCds.PatientRecord.Demographics.PhoneNumber>();
                }
                return this.phoneNumber;
            }

            /**
             * Gets the value of the enrolment property.
             * 
             * @return
             *     possible object is
             *     {@link OmdCds.PatientRecord.Demographics.Enrolment }
             *     
             */
            public OmdCds.PatientRecord.Demographics.Enrolment getEnrolment() {
                return enrolment;
            }

            /**
             * Sets the value of the enrolment property.
             * 
             * @param value
             *     allowed object is
             *     {@link OmdCds.PatientRecord.Demographics.Enrolment }
             *     
             */
            public void setEnrolment(OmdCds.PatientRecord.Demographics.Enrolment value) {
                this.enrolment = value;
            }

            /**
             * Gets the value of the primaryPhysician property.
             * 
             * @return
             *     possible object is
             *     {@link OmdCds.PatientRecord.Demographics.PrimaryPhysician }
             *     
             */
            public OmdCds.PatientRecord.Demographics.PrimaryPhysician getPrimaryPhysician() {
                return primaryPhysician;
            }

            /**
             * Sets the value of the primaryPhysician property.
             * 
             * @param value
             *     allowed object is
             *     {@link OmdCds.PatientRecord.Demographics.PrimaryPhysician }
             *     
             */
            public void setPrimaryPhysician(OmdCds.PatientRecord.Demographics.PrimaryPhysician value) {
                this.primaryPhysician = value;
            }

            /**
             * Gets the value of the email property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEmail() {
                return email;
            }

            /**
             * Sets the value of the email property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEmail(String value) {
                this.email = value;
            }

            /**
             * Gets the value of the personStatusCode property.
             * 
             * @return
             *     possible object is
             *     {@link OmdCds.PatientRecord.Demographics.PersonStatusCode }
             *     
             */
            public OmdCds.PatientRecord.Demographics.PersonStatusCode getPersonStatusCode() {
                return personStatusCode;
            }

            /**
             * Sets the value of the personStatusCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link OmdCds.PatientRecord.Demographics.PersonStatusCode }
             *     
             */
            public void setPersonStatusCode(OmdCds.PatientRecord.Demographics.PersonStatusCode value) {
                this.personStatusCode = value;
            }

            /**
             * Gets the value of the personStatusDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPersonStatusDate() {
                return personStatusDate;
            }

            /**
             * Sets the value of the personStatusDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPersonStatusDate(XMLGregorianCalendar value) {
                this.personStatusDate = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="EnrollmentStatus" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "enrollmentStatus"
            })
            public static class Enrolment {

                @XmlElement(name = "EnrollmentStatus")
                @XmlSchemaType(name = "unsignedByte")
                protected short enrollmentStatus;

                /**
                 * Gets the value of the enrollmentStatus property.
                 * 
                 */
                public short getEnrollmentStatus() {
                    return enrollmentStatus;
                }

                /**
                 * Sets the value of the enrollmentStatus property.
                 * 
                 */
                public void setEnrollmentStatus(short value) {
                    this.enrollmentStatus = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{cds_dt}Number"/>
             *         &lt;element ref="{cds_dt}ProvinceCode"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "number",
                "provinceCode"
            })
            public static class HealthCard {

                @XmlElement(name = "Number", namespace = "cds_dt", required = true)
                @XmlSchemaType(name = "unsignedLong")
                protected BigInteger number;
                @XmlElement(name = "ProvinceCode", namespace = "cds_dt", required = true)
                protected String provinceCode;

                /**
                 * Gets the value of the number property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getNumber() {
                    return number;
                }

                /**
                 * Sets the value of the number property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setNumber(BigInteger value) {
                    this.number = value;
                }

                /**
                 * Gets the value of the provinceCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getProvinceCode() {
                    return provinceCode;
                }

                /**
                 * Sets the value of the provinceCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setProvinceCode(String value) {
                    this.provinceCode = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{cds_dt}LegalName"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "legalName"
            })
            public static class Names {

                @XmlElement(name = "LegalName", namespace = "cds_dt", required = true)
                protected LegalName legalName;

                /**
                 * Gets the value of the legalName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link LegalName }
                 *     
                 */
                public LegalName getLegalName() {
                    return legalName;
                }

                /**
                 * Sets the value of the legalName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link LegalName }
                 *     
                 */
                public void setLegalName(LegalName value) {
                    this.legalName = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="PersonStatusAsEnum" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "personStatusAsEnum"
            })
            public static class PersonStatusCode {

                @XmlElement(name = "PersonStatusAsEnum", required = true)
                protected String personStatusAsEnum;

                /**
                 * Gets the value of the personStatusAsEnum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPersonStatusAsEnum() {
                    return personStatusAsEnum;
                }

                /**
                 * Sets the value of the personStatusAsEnum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPersonStatusAsEnum(String value) {
                    this.personStatusAsEnum = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{cds_dt}phoneNumber"/>
             *       &lt;/sequence>
             *       &lt;attribute name="phoneNumberType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "phoneNumber"
            })
            public static class PhoneNumber {

                @XmlElement(namespace = "cds_dt", required = true)
                @XmlSchemaType(name = "unsignedLong")
                protected BigInteger phoneNumber;
                @XmlAttribute(name = "phoneNumberType", required = true)
                protected String phoneNumberType;

                /**
                 * Gets the value of the phoneNumber property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getPhoneNumber() {
                    return phoneNumber;
                }

                /**
                 * Sets the value of the phoneNumber property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setPhoneNumber(BigInteger value) {
                    this.phoneNumber = value;
                }

                /**
                 * Gets the value of the phoneNumberType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPhoneNumberType() {
                    return phoneNumberType;
                }

                /**
                 * Sets the value of the phoneNumberType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPhoneNumberType(String value) {
                    this.phoneNumberType = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="OHIPPhysicianId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="Name">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element ref="{cds_dt}FirstName"/>
             *                   &lt;element ref="{cds_dt}LastName"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "ohipPhysicianId",
                "name"
            })
            public static class PrimaryPhysician {

                @XmlElement(name = "OHIPPhysicianId", required = true)
                protected Object ohipPhysicianId;
                @XmlElement(name = "Name", required = true)
                protected OmdCds.PatientRecord.Demographics.PrimaryPhysician.Name name;

                /**
                 * Gets the value of the ohipPhysicianId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getOHIPPhysicianId() {
                    return ohipPhysicianId;
                }

                /**
                 * Sets the value of the ohipPhysicianId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setOHIPPhysicianId(Object value) {
                    this.ohipPhysicianId = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link OmdCds.PatientRecord.Demographics.PrimaryPhysician.Name }
                 *     
                 */
                public OmdCds.PatientRecord.Demographics.PrimaryPhysician.Name getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link OmdCds.PatientRecord.Demographics.PrimaryPhysician.Name }
                 *     
                 */
                public void setName(OmdCds.PatientRecord.Demographics.PrimaryPhysician.Name value) {
                    this.name = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element ref="{cds_dt}FirstName"/>
                 *         &lt;element ref="{cds_dt}LastName"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "firstName",
                    "lastName"
                })
                public static class Name {

                    @XmlElement(name = "FirstName", namespace = "cds_dt", required = true)
                    protected String firstName;
                    @XmlElement(name = "LastName", namespace = "cds_dt", required = true)
                    protected String lastName;

                    /**
                     * Gets the value of the firstName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFirstName() {
                        return firstName;
                    }

                    /**
                     * Sets the value of the firstName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFirstName(String value) {
                        this.firstName = value;
                    }

                    /**
                     * Gets the value of the lastName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getLastName() {
                        return lastName;
                    }

                    /**
                     * Sets the value of the lastName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setLastName(String value) {
                        this.lastName = value;
                    }

                }

            }

        }

    }

}
