//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.22 at 05:00:32 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "cds_dt")
package org.oscarehr.common.xml.cds.v5_0.model;
