//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.23 at 02:21:20 PM PDT 
//


package org.oscarehr.common.xml.cds.v5_0.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for personNamePrefixCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="personNamePrefixCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;maxLength value="6"/>
 *     &lt;enumeration value="Bro"/>
 *     &lt;enumeration value="Capt"/>
 *     &lt;enumeration value="Chief"/>
 *     &lt;enumeration value="Cst"/>
 *     &lt;enumeration value="Corp"/>
 *     &lt;enumeration value="Dr"/>
 *     &lt;enumeration value="Fr"/>
 *     &lt;enumeration value="Hon"/>
 *     &lt;enumeration value="Lt"/>
 *     &lt;enumeration value="Madam"/>
 *     &lt;enumeration value="Mme"/>
 *     &lt;enumeration value="Mlle"/>
 *     &lt;enumeration value="Major"/>
 *     &lt;enumeration value="Mayor"/>
 *     &lt;enumeration value="Miss"/>
 *     &lt;enumeration value="Mr"/>
 *     &lt;enumeration value="Mssr"/>
 *     &lt;enumeration value="Mrs"/>
 *     &lt;enumeration value="Ms"/>
 *     &lt;enumeration value="Prof"/>
 *     &lt;enumeration value="Reeve"/>
 *     &lt;enumeration value="Rev"/>
 *     &lt;enumeration value="RtHon"/>
 *     &lt;enumeration value="Sen"/>
 *     &lt;enumeration value="Sgt"/>
 *     &lt;enumeration value="Sr"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "personNamePrefixCode")
@XmlEnum
public enum PersonNamePrefixCode {

    @XmlEnumValue("Bro")
    BRO("Bro"),
    @XmlEnumValue("Capt")
    CAPT("Capt"),
    @XmlEnumValue("Chief")
    CHIEF("Chief"),
    @XmlEnumValue("Cst")
    CST("Cst"),
    @XmlEnumValue("Corp")
    CORP("Corp"),
    @XmlEnumValue("Dr")
    DR("Dr"),
    @XmlEnumValue("Fr")
    FR("Fr"),
    @XmlEnumValue("Hon")
    HON("Hon"),
    @XmlEnumValue("Lt")
    LT("Lt"),
    @XmlEnumValue("Madam")
    MADAM("Madam"),
    @XmlEnumValue("Mme")
    MME("Mme"),
    @XmlEnumValue("Mlle")
    MLLE("Mlle"),
    @XmlEnumValue("Major")
    MAJOR("Major"),
    @XmlEnumValue("Mayor")
    MAYOR("Mayor"),
    @XmlEnumValue("Miss")
    MISS("Miss"),
    @XmlEnumValue("Mr")
    MR("Mr"),
    @XmlEnumValue("Mssr")
    MSSR("Mssr"),
    @XmlEnumValue("Mrs")
    MRS("Mrs"),
    @XmlEnumValue("Ms")
    MS("Ms"),
    @XmlEnumValue("Prof")
    PROF("Prof"),
    @XmlEnumValue("Reeve")
    REEVE("Reeve"),
    @XmlEnumValue("Rev")
    REV("Rev"),
    @XmlEnumValue("RtHon")
    RT_HON("RtHon"),
    @XmlEnumValue("Sen")
    SEN("Sen"),
    @XmlEnumValue("Sgt")
    SGT("Sgt"),
    @XmlEnumValue("Sr")
    SR("Sr");
    private final String value;

    PersonNamePrefixCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PersonNamePrefixCode fromValue(String v) {
        for (PersonNamePrefixCode c: PersonNamePrefixCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
