//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.23 at 02:21:20 PM PDT 
//


package org.oscarehr.common.xml.cds.v5_0.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for propertyOfOffendingAgent.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="propertyOfOffendingAgent">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;maxLength value="2"/>
 *     &lt;enumeration value="DR"/>
 *     &lt;enumeration value="ND"/>
 *     &lt;enumeration value="UK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "propertyOfOffendingAgent")
@XmlEnum
public enum PropertyOfOffendingAgent {

    DR,
    ND,
    UK;

    public String value() {
        return name();
    }

    public static PropertyOfOffendingAgent fromValue(String v) {
        return valueOf(v);
    }

}
