//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.23 at 02:21:20 PM PDT 
//


package org.oscarehr.common.xml.cds.v5_0.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for purposeEnumOrPlainText complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="purposeEnumOrPlainText">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="PurposeAsEnum">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *               &lt;enumeration value="EC"/>
 *               &lt;enumeration value="NK"/>
 *               &lt;enumeration value="AS"/>
 *               &lt;enumeration value="CG"/>
 *               &lt;enumeration value="PA"/>
 *               &lt;enumeration value="IN"/>
 *               &lt;enumeration value="GT"/>
 *               &lt;enumeration value="SDM"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PurposeAsPlainText">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "purposeEnumOrPlainText", propOrder = {
    "purposeAsEnum",
    "purposeAsPlainText"
})
public class PurposeEnumOrPlainText {

    @XmlElement(name = "PurposeAsEnum")
    protected String purposeAsEnum;
    @XmlElement(name = "PurposeAsPlainText")
    protected String purposeAsPlainText;

    /**
     * Gets the value of the purposeAsEnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurposeAsEnum() {
        return purposeAsEnum;
    }

    /**
     * Sets the value of the purposeAsEnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurposeAsEnum(String value) {
        this.purposeAsEnum = value;
    }

    /**
     * Gets the value of the purposeAsPlainText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurposeAsPlainText() {
        return purposeAsPlainText;
    }

    /**
     * Sets the value of the purposeAsPlainText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurposeAsPlainText(String value) {
        this.purposeAsPlainText = value;
    }

}
