//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.23 at 02:21:20 PM PDT 
//


package org.oscarehr.common.xml.cds.v5_0.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reportClass.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="reportClass">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;maxLength value="50"/>
 *     &lt;enumeration value="Diagnostic Imaging Report"/>
 *     &lt;enumeration value="Diagnostic Test Report"/>
 *     &lt;enumeration value="Cardio Respiratory Report"/>
 *     &lt;enumeration value="Medical Records Report"/>
 *     &lt;enumeration value="Consultant Report"/>
 *     &lt;enumeration value="Lab Report"/>
 *     &lt;enumeration value="Other Letter"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "reportClass")
@XmlEnum
public enum ReportClass {

    @XmlEnumValue("Diagnostic Imaging Report")
    DIAGNOSTIC_IMAGING_REPORT("Diagnostic Imaging Report"),
    @XmlEnumValue("Diagnostic Test Report")
    DIAGNOSTIC_TEST_REPORT("Diagnostic Test Report"),
    @XmlEnumValue("Cardio Respiratory Report")
    CARDIO_RESPIRATORY_REPORT("Cardio Respiratory Report"),
    @XmlEnumValue("Medical Records Report")
    MEDICAL_RECORDS_REPORT("Medical Records Report"),
    @XmlEnumValue("Consultant Report")
    CONSULTANT_REPORT("Consultant Report"),
    @XmlEnumValue("Lab Report")
    LAB_REPORT("Lab Report"),
    @XmlEnumValue("Other Letter")
    OTHER_LETTER("Other Letter");
    private final String value;

    ReportClass(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReportClass fromValue(String v) {
        for (ReportClass c: ReportClass.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
