//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.23 at 02:21:20 PM PDT 
//


package org.oscarehr.common.xml.cds.v5_0.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for resultNormalAbnormalFlag complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resultNormalAbnormalFlag">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="resultNormalAbnormalFlagAsEnum">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;maxLength value="2"/>
 *               &lt;enumeration value="L"/>
 *               &lt;enumeration value="LL"/>
 *               &lt;enumeration value="H"/>
 *               &lt;enumeration value="HH"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value="A"/>
 *               &lt;enumeration value="AA"/>
 *               &lt;enumeration value="S"/>
 *               &lt;enumeration value="R"/>
 *               &lt;enumeration value="I"/>
 *               &lt;enumeration value="MS"/>
 *               &lt;enumeration value="VS"/>
 *               &lt;enumeration value="U"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="resultNormalAbnormalFlagAsPlainText">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resultNormalAbnormalFlag", propOrder = {
    "resultNormalAbnormalFlagAsEnum",
    "resultNormalAbnormalFlagAsPlainText"
})
public class ResultNormalAbnormalFlag {

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String resultNormalAbnormalFlagAsEnum;
    protected String resultNormalAbnormalFlagAsPlainText;

    /**
     * Gets the value of the resultNormalAbnormalFlagAsEnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultNormalAbnormalFlagAsEnum() {
        return resultNormalAbnormalFlagAsEnum;
    }

    /**
     * Sets the value of the resultNormalAbnormalFlagAsEnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultNormalAbnormalFlagAsEnum(String value) {
        this.resultNormalAbnormalFlagAsEnum = value;
    }

    /**
     * Gets the value of the resultNormalAbnormalFlagAsPlainText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultNormalAbnormalFlagAsPlainText() {
        return resultNormalAbnormalFlagAsPlainText;
    }

    /**
     * Sets the value of the resultNormalAbnormalFlagAsPlainText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultNormalAbnormalFlagAsPlainText(String value) {
        this.resultNormalAbnormalFlagAsPlainText = value;
    }

}
