/**
 * Copyright (c) 2012-2018. CloudPractice Inc. All Rights Reserved.
 * This software is published under the GPL GNU General Public License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * This software was written for
 * CloudPractice Inc.
 * Victoria, British Columbia
 * Canada
 */
package org.oscarehr.security.model;

import org.oscarehr.managers.SecurityInfoManager;

public enum Permission
{
	//TODO - admin should be broken into sub-module config permissions. use single enum for now
	ADMIN_READ(SecObjectName.OBJECT_NAME.ADMIN, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	ADMIN_CREATE(SecObjectName.OBJECT_NAME.ADMIN, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	ADMIN_UPDATE(SecObjectName.OBJECT_NAME.ADMIN, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	ADMIN_DELETE(SecObjectName.OBJECT_NAME.ADMIN, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	APPOINTMENT_READ(SecObjectName.OBJECT_NAME.APPOINTMENT, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	APPOINTMENT_CREATE(SecObjectName.OBJECT_NAME.APPOINTMENT, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	APPOINTMENT_UPDATE(SecObjectName.OBJECT_NAME.APPOINTMENT, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	APPOINTMENT_DELETE(SecObjectName.OBJECT_NAME.APPOINTMENT, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	ALLERGY_READ(SecObjectName.OBJECT_NAME.ALLERGY, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	ALLERGY_CREATE(SecObjectName.OBJECT_NAME.ALLERGY, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	ALLERGY_UPDATE(SecObjectName.OBJECT_NAME.ALLERGY, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	ALLERGY_DELETE(SecObjectName.OBJECT_NAME.ALLERGY, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	AQS_QUEUED_APPOINTMENTS_READ(SecObjectName.OBJECT_NAME.AQS_QUEUED_APPOINTMENTS, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	AQS_QUEUED_APPOINTMENTS_CREATE(SecObjectName.OBJECT_NAME.AQS_QUEUED_APPOINTMENTS, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	AQS_QUEUED_APPOINTMENTS_UPDATE(SecObjectName.OBJECT_NAME.AQS_QUEUED_APPOINTMENTS, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	AQS_QUEUED_APPOINTMENTS_DELETE(SecObjectName.OBJECT_NAME.AQS_QUEUED_APPOINTMENTS, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	AQS_QUEUE_CONFIG_READ(SecObjectName.OBJECT_NAME.AQS_QUEUE_CONFIG, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	AQS_QUEUE_CONFIG_CREATE(SecObjectName.OBJECT_NAME.AQS_QUEUE_CONFIG, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	AQS_QUEUE_CONFIG_UPDATE(SecObjectName.OBJECT_NAME.AQS_QUEUE_CONFIG, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	AQS_QUEUE_CONFIG_DELETE(SecObjectName.OBJECT_NAME.AQS_QUEUE_CONFIG, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	BILLING_READ(SecObjectName.OBJECT_NAME.BILLING, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	BILLING_CREATE(SecObjectName.OBJECT_NAME.BILLING, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	BILLING_UPDATE(SecObjectName.OBJECT_NAME.BILLING, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	BILLING_DELETE(SecObjectName.OBJECT_NAME.BILLING, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	CARE_TRACKER_READ(SecObjectName.OBJECT_NAME.FLOWSHEET, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	CARE_TRACKER_CREATE(SecObjectName.OBJECT_NAME.FLOWSHEET, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	CARE_TRACKER_UPDATE(SecObjectName.OBJECT_NAME.FLOWSHEET, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	CARE_TRACKER_DELETE(SecObjectName.OBJECT_NAME.FLOWSHEET, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	CONFIGURE_BILLING_READ(SecObjectName.OBJECT_NAME.ADMIN_BILLING, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	CONFIGURE_BILLING_CREATE(SecObjectName.OBJECT_NAME.ADMIN_BILLING, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	CONFIGURE_BILLING_UPDATE(SecObjectName.OBJECT_NAME.ADMIN_BILLING, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	CONFIGURE_BILLING_DELETE(SecObjectName.OBJECT_NAME.ADMIN_BILLING, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	CONFIGURE_CONSULT_READ(SecObjectName.OBJECT_NAME.ADMIN_CONSULT, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	CONFIGURE_CONSULT_CREATE(SecObjectName.OBJECT_NAME.ADMIN_CONSULT, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	CONFIGURE_CONSULT_UPDATE(SecObjectName.OBJECT_NAME.ADMIN_CONSULT, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	CONFIGURE_CONSULT_DELETE(SecObjectName.OBJECT_NAME.ADMIN_CONSULT, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	CONFIGURE_FAX_READ(SecObjectName.OBJECT_NAME.FAX_CONFIG, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	CONFIGURE_FAX_CREATE(SecObjectName.OBJECT_NAME.FAX_CONFIG, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	CONFIGURE_FAX_UPDATE(SecObjectName.OBJECT_NAME.FAX_CONFIG, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	CONFIGURE_FAX_DELETE(SecObjectName.OBJECT_NAME.FAX_CONFIG, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	CONFIGURE_PROVIDER_READ(SecObjectName.OBJECT_NAME.ADMIN_USER_ADMIN, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	CONFIGURE_PROVIDER_CREATE(SecObjectName.OBJECT_NAME.ADMIN_USER_ADMIN, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	CONFIGURE_PROVIDER_UPDATE(SecObjectName.OBJECT_NAME.ADMIN_USER_ADMIN, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	CONFIGURE_PROVIDER_DELETE(SecObjectName.OBJECT_NAME.ADMIN_USER_ADMIN, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	CONFIGURE_SECURITY_ROLES_READ(SecObjectName.OBJECT_NAME.ADMIN_SECURITY, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	CONFIGURE_SECURITY_ROLES_CREATE(SecObjectName.OBJECT_NAME.ADMIN_SECURITY, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	CONFIGURE_SECURITY_ROLES_UPDATE(SecObjectName.OBJECT_NAME.ADMIN_SECURITY, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	CONFIGURE_SECURITY_ROLES_DELETE(SecObjectName.OBJECT_NAME.ADMIN_SECURITY, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	CONSULTATION_READ(SecObjectName.OBJECT_NAME.CONSULTATION, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	CONSULTATION_CREATE(SecObjectName.OBJECT_NAME.CONSULTATION, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	CONSULTATION_UPDATE(SecObjectName.OBJECT_NAME.CONSULTATION, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	CONSULTATION_DELETE(SecObjectName.OBJECT_NAME.CONSULTATION, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	CPP_NOTE_READ(SecObjectName.OBJECT_NAME.NEW_CASEMGMT_CPP, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	CPP_NOTE_CREATE(SecObjectName.OBJECT_NAME.NEW_CASEMGMT_CPP, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	CPP_NOTE_UPDATE(SecObjectName.OBJECT_NAME.NEW_CASEMGMT_CPP, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	CPP_NOTE_DELETE(SecObjectName.OBJECT_NAME.NEW_CASEMGMT_CPP, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	DECISION_SUPPORT_READ(SecObjectName.OBJECT_NAME.NEW_CASEMGMT_DECISION_SUPPORT_ALERTS, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	DECISION_SUPPORT_CREATE(SecObjectName.OBJECT_NAME.NEW_CASEMGMT_DECISION_SUPPORT_ALERTS, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	DECISION_SUPPORT_UPDATE(SecObjectName.OBJECT_NAME.NEW_CASEMGMT_DECISION_SUPPORT_ALERTS, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	DECISION_SUPPORT_DELETE(SecObjectName.OBJECT_NAME.NEW_CASEMGMT_DECISION_SUPPORT_ALERTS, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	DEMOGRAPHIC_READ(SecObjectName.OBJECT_NAME.DEMOGRAPHIC, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	DEMOGRAPHIC_CREATE(SecObjectName.OBJECT_NAME.DEMOGRAPHIC, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	DEMOGRAPHIC_UPDATE(SecObjectName.OBJECT_NAME.DEMOGRAPHIC, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	DEMOGRAPHIC_DELETE(SecObjectName.OBJECT_NAME.DEMOGRAPHIC, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	DEMOGRAPHIC_EXPORT_READ(SecObjectName.OBJECT_NAME.DEMOGRAPHIC_EXPORT, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	DEMOGRAPHIC_EXPORT_CREATE(SecObjectName.OBJECT_NAME.DEMOGRAPHIC_EXPORT, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	DEMOGRAPHIC_EXPORT_UPDATE(SecObjectName.OBJECT_NAME.DEMOGRAPHIC_EXPORT, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	DEMOGRAPHIC_EXPORT_DELETE(SecObjectName.OBJECT_NAME.DEMOGRAPHIC_EXPORT, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	DEMOGRAPHIC_IMPORT_READ(SecObjectName.OBJECT_NAME.DEMOGRAPHIC_IMPORT, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	DEMOGRAPHIC_IMPORT_CREATE(SecObjectName.OBJECT_NAME.DEMOGRAPHIC_IMPORT, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	DEMOGRAPHIC_IMPORT_UPDATE(SecObjectName.OBJECT_NAME.DEMOGRAPHIC_IMPORT, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	DEMOGRAPHIC_IMPORT_DELETE(SecObjectName.OBJECT_NAME.DEMOGRAPHIC_IMPORT, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	DOCUMENT_READ(SecObjectName.OBJECT_NAME.EDOC, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	DOCUMENT_CREATE(SecObjectName.OBJECT_NAME.EDOC, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	DOCUMENT_UPDATE(SecObjectName.OBJECT_NAME.EDOC, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	DOCUMENT_DELETE(SecObjectName.OBJECT_NAME.EDOC, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	DX_READ(SecObjectName.OBJECT_NAME.DXRESEARCH, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	DX_CREATE(SecObjectName.OBJECT_NAME.DXRESEARCH, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	DX_UPDATE(SecObjectName.OBJECT_NAME.DXRESEARCH, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	DX_DELETE(SecObjectName.OBJECT_NAME.DXRESEARCH, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	ECHART_READ(SecObjectName.OBJECT_NAME.ECHART, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	ECHART_CREATE(SecObjectName.OBJECT_NAME.ECHART, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	ECHART_UPDATE(SecObjectName.OBJECT_NAME.ECHART, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	ECHART_DELETE(SecObjectName.OBJECT_NAME.ECHART, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	EFORM_READ(SecObjectName.OBJECT_NAME.EFORM, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	EFORM_CREATE(SecObjectName.OBJECT_NAME.EFORM, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	EFORM_UPDATE(SecObjectName.OBJECT_NAME.EFORM, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	EFORM_DELETE(SecObjectName.OBJECT_NAME.EFORM, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	ENCOUNTER_ISSUE_READ(SecObjectName.OBJECT_NAME.CASEMGMT_ISSUES, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	ENCOUNTER_ISSUE_CREATE(SecObjectName.OBJECT_NAME.CASEMGMT_ISSUES, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	ENCOUNTER_ISSUE_UPDATE(SecObjectName.OBJECT_NAME.CASEMGMT_ISSUES, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	ENCOUNTER_ISSUE_DELETE(SecObjectName.OBJECT_NAME.CASEMGMT_ISSUES, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	ENCOUNTER_NOTE_READ(SecObjectName.OBJECT_NAME.CASEMGMT_NOTES, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	ENCOUNTER_NOTE_CREATE(SecObjectName.OBJECT_NAME.CASEMGMT_NOTES, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	ENCOUNTER_NOTE_UPDATE(SecObjectName.OBJECT_NAME.CASEMGMT_NOTES, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	ENCOUNTER_NOTE_DELETE(SecObjectName.OBJECT_NAME.CASEMGMT_NOTES, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	FAX_READ(SecObjectName.OBJECT_NAME.FAX_DOCUMENTS, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	FAX_CREATE(SecObjectName.OBJECT_NAME.FAX_DOCUMENTS, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	FAX_UPDATE(SecObjectName.OBJECT_NAME.FAX_DOCUMENTS, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	FAX_DELETE(SecObjectName.OBJECT_NAME.FAX_DOCUMENTS, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	FORM_READ(SecObjectName.OBJECT_NAME.FORM, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	FORM_CREATE(SecObjectName.OBJECT_NAME.FORM, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	FORM_UPDATE(SecObjectName.OBJECT_NAME.FORM, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	FORM_DELETE(SecObjectName.OBJECT_NAME.FORM, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	HRM_READ(SecObjectName.OBJECT_NAME.HRM, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	HRM_CREATE(SecObjectName.OBJECT_NAME.HRM, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	HRM_UPDATE(SecObjectName.OBJECT_NAME.HRM, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	HRM_DELETE(SecObjectName.OBJECT_NAME.HRM, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	K2A_READ(SecObjectName.OBJECT_NAME.APP_DEFINITION, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	K2A_CREATE(SecObjectName.OBJECT_NAME.APP_DEFINITION, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	K2A_UPDATE(SecObjectName.OBJECT_NAME.APP_DEFINITION, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	K2A_DELETE(SecObjectName.OBJECT_NAME.APP_DEFINITION, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	LAB_READ(SecObjectName.OBJECT_NAME.LAB, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	LAB_CREATE(SecObjectName.OBJECT_NAME.LAB, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	LAB_UPDATE(SecObjectName.OBJECT_NAME.LAB, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	LAB_DELETE(SecObjectName.OBJECT_NAME.LAB, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	MEASUREMENT_READ(SecObjectName.OBJECT_NAME.MEASUREMENT, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	MEASUREMENT_CREATE(SecObjectName.OBJECT_NAME.MEASUREMENT, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	MEASUREMENT_UPDATE(SecObjectName.OBJECT_NAME.MEASUREMENT, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	MEASUREMENT_DELETE(SecObjectName.OBJECT_NAME.MEASUREMENT, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	MESSAGE_READ(SecObjectName.OBJECT_NAME.MESSAGE, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	MESSAGE_CREATE(SecObjectName.OBJECT_NAME.MESSAGE, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	MESSAGE_UPDATE(SecObjectName.OBJECT_NAME.MESSAGE, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	MESSAGE_DELETE(SecObjectName.OBJECT_NAME.MESSAGE, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	PREFERENCE_READ(SecObjectName.OBJECT_NAME.PREF, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	PREFERENCE_CREATE(SecObjectName.OBJECT_NAME.PREF, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	PREFERENCE_UPDATE(SecObjectName.OBJECT_NAME.PREF, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	PREFERENCE_DELETE(SecObjectName.OBJECT_NAME.PREF, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	PREVENTION_READ(SecObjectName.OBJECT_NAME.PREVENTION, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	PREVENTION_CREATE(SecObjectName.OBJECT_NAME.PREVENTION, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	PREVENTION_UPDATE(SecObjectName.OBJECT_NAME.PREVENTION, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	PREVENTION_DELETE(SecObjectName.OBJECT_NAME.PREVENTION, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	REPORT_READ(SecObjectName.OBJECT_NAME.REPORT, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	REPORT_CREATE(SecObjectName.OBJECT_NAME.REPORT, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	REPORT_UPDATE(SecObjectName.OBJECT_NAME.REPORT, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	REPORT_DELETE(SecObjectName.OBJECT_NAME.REPORT, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	RX_READ(SecObjectName.OBJECT_NAME.RX, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	RX_CREATE(SecObjectName.OBJECT_NAME.RX, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	RX_UPDATE(SecObjectName.OBJECT_NAME.RX, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	RX_DELETE(SecObjectName.OBJECT_NAME.RX, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	TASK_READ(SecObjectName.OBJECT_NAME.TASKS, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	TASK_CREATE(SecObjectName.OBJECT_NAME.TASKS, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	TASK_UPDATE(SecObjectName.OBJECT_NAME.TASKS, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	TASK_DELETE(SecObjectName.OBJECT_NAME.TASKS, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE),

	TICKLER_READ(SecObjectName.OBJECT_NAME.TICKLER, SecurityInfoManager.PRIVILEGE_LEVEL.READ),
	TICKLER_CREATE(SecObjectName.OBJECT_NAME.TICKLER, SecurityInfoManager.PRIVILEGE_LEVEL.CREATE),
	TICKLER_UPDATE(SecObjectName.OBJECT_NAME.TICKLER, SecurityInfoManager.PRIVILEGE_LEVEL.UPDATE),
	TICKLER_DELETE(SecObjectName.OBJECT_NAME.TICKLER, SecurityInfoManager.PRIVILEGE_LEVEL.DELETE);

	private final SecObjectName.OBJECT_NAME objectName;
	private final SecurityInfoManager.PRIVILEGE_LEVEL privilegeLevel;

	Permission(SecObjectName.OBJECT_NAME objectName, SecurityInfoManager.PRIVILEGE_LEVEL privilegeLevel)
	{
		this.objectName = objectName;
		this.privilegeLevel = privilegeLevel;
	}

	public SecObjectName.OBJECT_NAME getObjectName()
	{
		return this.objectName;
	}

	public SecurityInfoManager.PRIVILEGE_LEVEL getPrivilegeLevel()
	{
		return this.privilegeLevel;
	}

	public static Permission from(SecObjectName.OBJECT_NAME objectName, SecurityInfoManager.PRIVILEGE_LEVEL privilegeLevel)
	{
		for (Permission permission : Permission.values())
		{
			if (permission.getObjectName().equals(objectName) && permission.getPrivilegeLevel().equals(privilegeLevel))
			{
				return permission;
			}
		}
		return null;
	}

	/**
	 * allow us to identify OBJECT_NAME(s) that are used by this enum
	 * @param objectName - the object to check for
	 * @return true if one or more Permission include this object as a value
	 */
	public static boolean includesObjectAsValue(SecObjectName.OBJECT_NAME objectName)
	{
		for (Permission permission : Permission.values())
		{
			if(permission.getObjectName().equals(objectName))
			{
				return true;
			}
		}
		return false;
	}
}
