/**
 * Copyright (c) 2001-2002. Department of Family Medicine, McMaster University. All Rights Reserved.
 * This software is published under the GPL GNU General Public License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * This software was written for the
 * Department of Family Medicine
 * McMaster University
 * Hamilton
 * Ontario, Canada
 */


package org.oscarehr.security.model;

import lombok.Data;
import org.hibernate.annotations.Where;
import org.oscarehr.common.model.AbstractModel;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;
import java.time.LocalDateTime;

import static org.oscarehr.managers.SecurityInfoManager.PRIVILEGE_LEVEL;
import static org.oscarehr.security.model.SecObjectName.OBJECT_NAME;

@Data
@Entity
@Table(name = "secObjPrivilege")
@Where(clause="deleted_at IS NULL")
public class SecObjPrivilege extends AbstractModel<SecObjPrivilegePrimaryKey>
{
	public enum PERMISSION
	{
		APPOINTMENT_READ(OBJECT_NAME.APPOINTMENT, PRIVILEGE_LEVEL.READ),
		APPOINTMENT_CREATE(OBJECT_NAME.APPOINTMENT, PRIVILEGE_LEVEL.CREATE),
		APPOINTMENT_UPDATE(OBJECT_NAME.APPOINTMENT, PRIVILEGE_LEVEL.UPDATE),
		APPOINTMENT_DELETE(OBJECT_NAME.APPOINTMENT, PRIVILEGE_LEVEL.DELETE),

		AQS_QUEUED_APPOINTMENTS_READ(OBJECT_NAME.AQS_QUEUED_APPOINTMENTS, PRIVILEGE_LEVEL.READ),
		AQS_QUEUED_APPOINTMENTS_CREATE(OBJECT_NAME.AQS_QUEUED_APPOINTMENTS, PRIVILEGE_LEVEL.CREATE),
		AQS_QUEUED_APPOINTMENTS_UPDATE(OBJECT_NAME.AQS_QUEUED_APPOINTMENTS, PRIVILEGE_LEVEL.UPDATE),
		AQS_QUEUED_APPOINTMENTS_DELETE(OBJECT_NAME.AQS_QUEUED_APPOINTMENTS, PRIVILEGE_LEVEL.DELETE),

		AQS_QUEUE_CONFIG_READ(OBJECT_NAME.AQS_QUEUE_CONFIG, PRIVILEGE_LEVEL.READ),
		AQS_QUEUE_CONFIG_CREATE(OBJECT_NAME.AQS_QUEUE_CONFIG, PRIVILEGE_LEVEL.CREATE),
		AQS_QUEUE_CONFIG_UPDATE(OBJECT_NAME.AQS_QUEUE_CONFIG, PRIVILEGE_LEVEL.UPDATE),
		AQS_QUEUE_CONFIG_DELETE(OBJECT_NAME.AQS_QUEUE_CONFIG, PRIVILEGE_LEVEL.DELETE),

		CONFIGURE_BILLING_READ(OBJECT_NAME.ADMIN_BILLING, PRIVILEGE_LEVEL.READ),
		CONFIGURE_BILLING_CREATE(OBJECT_NAME.ADMIN_BILLING, PRIVILEGE_LEVEL.CREATE),
		CONFIGURE_BILLING_UPDATE(OBJECT_NAME.ADMIN_BILLING, PRIVILEGE_LEVEL.UPDATE),
		CONFIGURE_BILLING_DELETE(OBJECT_NAME.ADMIN_BILLING, PRIVILEGE_LEVEL.DELETE),

		CONFIGURE_CONSULT_READ(OBJECT_NAME.ADMIN_CONSULT, PRIVILEGE_LEVEL.READ),
		CONFIGURE_CONSULT_CREATE(OBJECT_NAME.ADMIN_CONSULT, PRIVILEGE_LEVEL.CREATE),
		CONFIGURE_CONSULT_UPDATE(OBJECT_NAME.ADMIN_CONSULT, PRIVILEGE_LEVEL.UPDATE),
		CONFIGURE_CONSULT_DELETE(OBJECT_NAME.ADMIN_CONSULT, PRIVILEGE_LEVEL.DELETE),

		CONFIGURE_SECURITY_ROLES_READ(OBJECT_NAME.ADMIN_SECURITY, PRIVILEGE_LEVEL.READ),
		CONFIGURE_SECURITY_ROLES_CREATE(OBJECT_NAME.ADMIN_SECURITY, PRIVILEGE_LEVEL.CREATE),
		CONFIGURE_SECURITY_ROLES_UPDATE(OBJECT_NAME.ADMIN_SECURITY, PRIVILEGE_LEVEL.UPDATE),
		CONFIGURE_SECURITY_ROLES_DELETE(OBJECT_NAME.ADMIN_SECURITY, PRIVILEGE_LEVEL.DELETE),

		CONSULTATION_READ(OBJECT_NAME.CONSULTATION, PRIVILEGE_LEVEL.READ),
		CONSULTATION_CREATE(OBJECT_NAME.CONSULTATION, PRIVILEGE_LEVEL.CREATE),
		CONSULTATION_UPDATE(OBJECT_NAME.CONSULTATION, PRIVILEGE_LEVEL.UPDATE),
		CONSULTATION_DELETE(OBJECT_NAME.CONSULTATION, PRIVILEGE_LEVEL.DELETE),

		DEMOGRAPHIC_READ(OBJECT_NAME.DEMOGRAPHIC, PRIVILEGE_LEVEL.READ),
		DEMOGRAPHIC_CREATE(OBJECT_NAME.DEMOGRAPHIC, PRIVILEGE_LEVEL.CREATE),
		DEMOGRAPHIC_UPDATE(OBJECT_NAME.DEMOGRAPHIC, PRIVILEGE_LEVEL.UPDATE),
		DEMOGRAPHIC_DELETE(OBJECT_NAME.DEMOGRAPHIC, PRIVILEGE_LEVEL.DELETE),

		DOCUMENT_READ(OBJECT_NAME.EDOC, PRIVILEGE_LEVEL.READ),
		DOCUMENT_CREATE(OBJECT_NAME.EDOC, PRIVILEGE_LEVEL.CREATE),
		DOCUMENT_UPDATE(OBJECT_NAME.EDOC, PRIVILEGE_LEVEL.UPDATE),
		DOCUMENT_DELETE(OBJECT_NAME.EDOC, PRIVILEGE_LEVEL.DELETE),

		HRM_READ(OBJECT_NAME.HRM, PRIVILEGE_LEVEL.READ),
		HRM_CREATE(OBJECT_NAME.HRM, PRIVILEGE_LEVEL.CREATE),
		HRM_UPDATE(OBJECT_NAME.HRM, PRIVILEGE_LEVEL.UPDATE),
		HRM_DELETE(OBJECT_NAME.HRM, PRIVILEGE_LEVEL.DELETE),

		K2A_READ(OBJECT_NAME.APP_DEFINITION, PRIVILEGE_LEVEL.READ),
		K2A_CREATE(OBJECT_NAME.APP_DEFINITION, PRIVILEGE_LEVEL.CREATE),
		K2A_UPDATE(OBJECT_NAME.APP_DEFINITION, PRIVILEGE_LEVEL.UPDATE),
		K2A_DELETE(OBJECT_NAME.APP_DEFINITION, PRIVILEGE_LEVEL.DELETE),

		LAB_READ(OBJECT_NAME.LAB, PRIVILEGE_LEVEL.READ),
		LAB_CREATE(OBJECT_NAME.LAB, PRIVILEGE_LEVEL.CREATE),
		LAB_UPDATE(OBJECT_NAME.LAB, PRIVILEGE_LEVEL.UPDATE),
		LAB_DELETE(OBJECT_NAME.LAB, PRIVILEGE_LEVEL.DELETE),

		MEASUREMENT_READ(OBJECT_NAME.MEASUREMENT, PRIVILEGE_LEVEL.READ),
		MEASUREMENT_CREATE(OBJECT_NAME.MEASUREMENT, PRIVILEGE_LEVEL.CREATE),
		MEASUREMENT_UPDATE(OBJECT_NAME.MEASUREMENT, PRIVILEGE_LEVEL.UPDATE),
		MEASUREMENT_DELETE(OBJECT_NAME.MEASUREMENT, PRIVILEGE_LEVEL.DELETE),

		MESSAGE_READ(OBJECT_NAME.MESSAGE, PRIVILEGE_LEVEL.READ),
		MESSAGE_CREATE(OBJECT_NAME.MESSAGE, PRIVILEGE_LEVEL.CREATE),
		MESSAGE_UPDATE(OBJECT_NAME.MESSAGE, PRIVILEGE_LEVEL.UPDATE),
		MESSAGE_DELETE(OBJECT_NAME.MESSAGE, PRIVILEGE_LEVEL.DELETE),

		REPORT_READ(OBJECT_NAME.REPORT, PRIVILEGE_LEVEL.READ),
		REPORT_CREATE(OBJECT_NAME.REPORT, PRIVILEGE_LEVEL.CREATE),
		REPORT_UPDATE(OBJECT_NAME.REPORT, PRIVILEGE_LEVEL.UPDATE),
		REPORT_DELETE(OBJECT_NAME.REPORT, PRIVILEGE_LEVEL.DELETE),

		TICKLER_READ(OBJECT_NAME.TICKLER, PRIVILEGE_LEVEL.READ),
		TICKLER_CREATE(OBJECT_NAME.TICKLER, PRIVILEGE_LEVEL.CREATE),
		TICKLER_UPDATE(OBJECT_NAME.TICKLER, PRIVILEGE_LEVEL.UPDATE),
		TICKLER_DELETE(OBJECT_NAME.TICKLER, PRIVILEGE_LEVEL.DELETE);

		private final OBJECT_NAME objectName;
		private final PRIVILEGE_LEVEL privilegeLevel;

		PERMISSION(OBJECT_NAME objectName, PRIVILEGE_LEVEL privilegeLevel)
		{
			this.objectName = objectName;
			this.privilegeLevel = privilegeLevel;
		}

		public OBJECT_NAME getObjectName()
		{
			return this.objectName;
		}

		public PRIVILEGE_LEVEL getPrivilegeLevel()
		{
			return this.privilegeLevel;
		}

		public static PERMISSION from(OBJECT_NAME objectName, PRIVILEGE_LEVEL privilegeLevel)
		{
			for (PERMISSION permission : PERMISSION.values())
			{
				if (permission.getObjectName().equals(objectName) && permission.getPrivilegeLevel().equals(privilegeLevel))
				{
					return permission;
				}
			}
			return null;
		}
	}

	@EmbeddedId
	private SecObjPrivilegePrimaryKey id;

	private String privilege = "|0|";

	private int priority = 0;

	@Column(name = "provider_no")
	private String providerNo = null;

	@Deprecated // property/column to be removed once all references use roleId
	private String roleUserGroup;

	@Column(name = "deleted_at", columnDefinition = "TIMESTAMP")
	private LocalDateTime deletedAt;

	@MapsId("secRoleId")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "secRoleId", referencedColumnName = "role_no", nullable = false, insertable = false, updatable = false)
	private SecRole secRole;

	@MapsId("objectName")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "objectName", referencedColumnName = "objectName", nullable = false, insertable = false, updatable = false)
	private SecObjectName secObjectName;

	@Override
	public SecObjPrivilegePrimaryKey getId()
	{
		return id;
	}

	@Override
	public int hashCode()
	{
		return this.id.hashCode();
	}
}
