//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.08 at 02:19:15 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "cds_dt", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.oscarehr.common.xml.hrm.v4_3.model;
