//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.08 at 02:19:15 PM PST 
//


package org.oscarehr.common.xml.hrm.v4_3.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for personNamePartQualifierCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="personNamePartQualifierCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;maxLength value="2"/>
 *     &lt;enumeration value="BR"/>
 *     &lt;enumeration value="SP"/>
 *     &lt;enumeration value="CL"/>
 *     &lt;enumeration value="IN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "personNamePartQualifierCode")
@XmlEnum
public enum PersonNamePartQualifierCode {

    BR,
    SP,
    CL,
    IN;

    public String value() {
        return name();
    }

    public static PersonNamePartQualifierCode fromValue(String v) {
        return valueOf(v);
    }

}
