//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.08 at 02:19:15 PM PST 
//


package org.oscarehr.common.xml.hrm.v4_3.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for phoneNumber complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="phoneNumber">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="phoneNumber">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;maxLength value="25"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="extension" type="{cds_dt}phoneExtension" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="areaCode" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *           &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *           &lt;element name="extension" type="{cds_dt}phoneExtension" minOccurs="0"/>
 *           &lt;element name="exchange" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute name="phoneNumberType" use="required" type="{cds_dt}phoneNumberType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "phoneNumber", propOrder = {
    "content"
})
public class PhoneNumber {

    @XmlElementRefs({
        @XmlElementRef(name = "number", namespace = "cds_dt", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "extension", namespace = "cds_dt", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "exchange", namespace = "cds_dt", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "phoneNumber", namespace = "cds_dt", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "areaCode", namespace = "cds_dt", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<String>> content;
    @XmlAttribute(name = "phoneNumberType", required = true)
    protected PhoneNumberType phoneNumberType;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Extension" is used by two different parts of a schema. See: 
     * line 546 of file:/mnt/robert.junoemr.com/oscarhost/source/oscar_emr/src/main/java/org/oscarehr/common/xml/hrm/v4_3/schema/report_manager_dt.xsd
     * line 541 of file:/mnt/robert.junoemr.com/oscarhost/source/oscar_emr/src/main/java/org/oscarehr/common/xml/hrm/v4_3/schema/report_manager_dt.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<String>>();
        }
        return this.content;
    }

    /**
     * Gets the value of the phoneNumberType property.
     * 
     * @return
     *     possible object is
     *     {@link PhoneNumberType }
     *     
     */
    public PhoneNumberType getPhoneNumberType() {
        return phoneNumberType;
    }

    /**
     * Sets the value of the phoneNumberType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhoneNumberType }
     *     
     */
    public void setPhoneNumberType(PhoneNumberType value) {
        this.phoneNumberType = value;
    }

}
