CREATE TABLE IF NOT EXISTS `billingmaster_clinicaid` (
  `billingmaster_no` int(10) NOT NULL AUTO_INCREMENT,
  `billing_no` int(10) NOT NULL DEFAULT '0',
  `createdate` datetime DEFAULT NULL,
  `billingstatus` char(1) DEFAULT NULL,
  `demographic_no` int(10) DEFAULT '0',
  `appointment_no` int(10) DEFAULT '0',
  `claimcode` char(3) DEFAULT 'C02',
  `datacenter` varchar(5) DEFAULT '00000',
  `payee_no` varchar(5) DEFAULT '00000',
  `practitioner_no` varchar(5) DEFAULT '00000',
  `phn` varchar(10) DEFAULT '0000000000',
  `name_verify` varchar(4) DEFAULT '',
  `dependent_num` char(2) DEFAULT '00',
  `billing_unit` char(3) DEFAULT '000',
  `clarification_code` char(2) DEFAULT '00',
  `anatomical_area` char(2) DEFAULT NULL,
  `after_hour` char(1) DEFAULT '0',
  `new_program` char(2) DEFAULT '00',
  `billing_code` varchar(10) DEFAULT '00000',
  `bill_amount` varchar(9) DEFAULT '000000000',
  `payment_mode` char(1) DEFAULT '0',
  `service_date` varchar(8) DEFAULT '00000000',
  `service_to_day` char(2) DEFAULT '00',
  `submission_code` char(1) DEFAULT '0',
  `extended_submission_code` char(1) DEFAULT '',
  `dx_code1` varchar(5) DEFAULT '',
  `dx_code2` varchar(5) DEFAULT '',
  `dx_code3` varchar(5) DEFAULT '',
  `dx_expansion` varchar(15) DEFAULT '',
  `service_location` char(1) DEFAULT '0',
  `referral_flag1` char(1) DEFAULT '0',
  `referral_no1` varchar(5) DEFAULT '00000',
  `referral_flag2` char(1) DEFAULT '0',
  `referral_no2` varchar(5) DEFAULT '00000',
  `time_call` varchar(4) DEFAULT '0000',
  `service_start_time` varchar(4) DEFAULT '0000',
  `service_end_time` varchar(4) DEFAULT '0000',
  `birth_date` varchar(8) DEFAULT '00000000',
  `office_number` varchar(7) DEFAULT '0000000',
  `correspondence_code` char(1) DEFAULT '0',
  `claim_comment` varchar(20) DEFAULT NULL,
  `mva_claim_code` char(1) DEFAULT 'N',
  `icbc_claim_no` varchar(8) DEFAULT '00000000',
  `original_claim` varchar(20) DEFAULT '00000000000000000000',
  `facility_no` varchar(5) DEFAULT '00000',
  `facility_sub_no` varchar(5) DEFAULT '00000',
  `filler_claim` varchar(58) DEFAULT NULL,
  `oin_insurer_code` char(2) DEFAULT '',
  `oin_registration_no` varchar(12) DEFAULT '',
  `oin_birthdate` varchar(8) DEFAULT '',
  `oin_first_name` varchar(12) DEFAULT '',
  `oin_second_name` char(1) DEFAULT '',
  `oin_surname` varchar(18) DEFAULT '',
  `oin_sex_code` char(1) DEFAULT '',
  `oin_address` varchar(25) DEFAULT '',
  `oin_address2` varchar(25) DEFAULT '',
  `oin_address3` varchar(25) DEFAULT '',
  `oin_address4` varchar(25) DEFAULT '',
  `oin_postalcode` varchar(6) DEFAULT '',
  `paymentMethod` int(11) DEFAULT '6',
  `wcb_id` int(10) DEFAULT NULL,
  `sequence_no` int(10) DEFAULT NULL,
  `invoice_creation_year` int(10) DEFAULT NULL,
  `data_center_no` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`billingmaster_no`),
  UNIQUE KEY `sequence_no-invoice_creation_year-data_center_no` (`sequence_no`, `invoice_creation_year`, `data_center_no`),
  KEY `billingmaster_wcb_id` (`wcb_id`),
  KEY `billingmaster_billingstatus` (`billingstatus`),
  KEY `billingmaster_billing_no` (`billing_no`),
  KEY `idx_billingmaster_demographic_no` (`demographic_no`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

CREATE VIEW IF NOT EXISTS dashboard_report_view AS
SELECT
  `billingmaster_no`, `createdate`, `billingstatus`, `demographic_no`, `payee_no`, `practitioner_no`, `billing_code`, `service_date`, `dx_code1`, `dx_code2`, `dx_code3`
FROM billingmaster
UNION ALL
SELECT
  `billingmaster_no`, `createdate`, `billingstatus`, `demographic_no`, `payee_no`, `practitioner_no`, `billing_code`, `service_date`, `dx_code1`, `dx_code2`, `dx_code3`
FROM billingmaster_clinicaid;