CREATE TABLE IF NOT EXISTS alberta_functional_centers (
  id INT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(4),
  description VARCHAR(30),
  CONSTRAINT uiq_code_description UNIQUE (code, description)
);

INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('AACC','Advanced Ambulatory Care Ctr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('AEOR','Exam/Lab/Surg/Elec/Othr/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('AIEO','Exam/Lab/Surg/Imag/Elec/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('AIER','Exam/Lab/Surg/Imag/Elec/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('AIOR','Exam/Lab/Surg/Imag/Othr/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('CEOR','Exam/Lab/Elec/Othr/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('CIEO','Exam/Lab/Imag/Elec/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('CIER','Exam/Lab/Imag/Elec/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('CIOR','Exam/Lab/Imag/Othr/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('CLAB','Clinical Laboratory');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('CLNC','Clinic');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('CSEO','Exam/Lab/Surg/Elec/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('CSER','Exam/Lab/Surg/Elec/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('CSIE','Exam/Lab/Surg/Imag/Elec');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('CSIO','Exam/Lab/Surg/Imag/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('CSIR','Exam/Lab/Surg/Imag/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('CSOR','Exam/Lab/Surg/Othr/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('D/N','Day/Night Care');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('DIMG','Diagnostic Imaging');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EALL','Exm/Lab/Srg/Imag/Elec/Othr/Res');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ECDT','Exam/Lab/Imag/Elec/Othr/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ECEO','Exam/Lab/Elec/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ECER','Exam/Lab/Elec/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ECIE','Exam/Lab/Imag/Elec');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ECIO','Exam/Lab/Imag/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ECIR','Exam/Lab/Imag/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ECOR','Exam/Lab/Othr/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EEOR','Exam/Elec/Othr/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EIEO','Exam/Imag/Elec/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EIER','Exam/Imag/Elec/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EIOR','Exam/Imag/Othr/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ELEC','Electrodiagnosis');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EMRG','Emergency');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ESCE','Exam/Surg/Lab/Elec');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ESCI','Exam/Surg/Lab/Imag');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ESCO','Exam/Surg/Lab/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ESCR','Exam/Surg/Lab/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ESDT','Exam/Surg/Imag/Elec/Othr/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ESEO','Exam/Surg/Elec/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ESER','Exam/Surg/Elec/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ESIE','Exam/Surg/Imag/Elec');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ESIO','Exam/Surg/Imag/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ESIR','Exam/Surg/Imag/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ESOR','Exam/Surg/Othr/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXCE','Exam/Lab/Elec');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXCI','Exam/Lab/Imag');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXCO','Exam/Lab/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXCR','Exam/Lab/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXDI','Exam/Imag');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXDT','Exam/Imag/Elec/Othr/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXED','Exam/Elec');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXEO','Exam/Elec/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXER','Exam/Elec/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXHB','Exmination Rm/Hyperbaric Chbr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXIE','Exam/Imag/Elec');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXIO','Exam/Imag/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXIR','Exam/Imag/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXOD','Exam/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXOR','Exam/Othr/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXRM','Examination Room');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXRT','Exam/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXSE','Exam/Surg/Elec');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXSI','Exam/Surg/Imag');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXSO','Exam/Surg/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('EXSR','Exam/Surg/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('FCC','Family Care Clinic');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('HBOC','Hyperbaric Oxygen Chamber');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ICN1','ICU Neonatal - Level 1');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ICN2','ICU Neonatal - level 2');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ICN3','ICU Neonatal - Level 3');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ICO1','ICU Obstetrics - Level 1');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ICO2','ICU Obstetrics - Level 2');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ICO3','ICU Obstetrics - Level 3');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ICU1','Intensive Care Unit - Level 1');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ICU2','Intensive Care Unit - Level 2');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('ICU3','Intensive Care Unit - Level 3');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('LBER','Clinical Lab/Examination Room');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('LSSE','Clin Lab/Surg Suite/Exam Room');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('LTC','Long Term Care');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('MED','Medical');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('OLAB','Other Diagnostic Laboratory');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('PCLN','LPCI Clinic');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('PEMG','Pediatric Emergency');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('PHYS','Physical Therapy');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('POOL','Pool Area');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('PRGR','Patient Room/Group Room');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('RDON','Radiation Oncology');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('RESP','Respiratory Therapy');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('SEOR','Exam/Surg/Elec/Othr/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('SGSU','Surgical Suite/Examination Rm');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('SIEO','Exam/Surg/Imag/Elec/Othr');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('SIER','Exam/Surg/Imag/Elec/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('SIOR','Exam/Surg/Imag/Othr/Resp');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('SURG','Surgical');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('UCC','Urgent Care Center');
INSERT IGNORE INTO alberta_functional_centers (code, description) VALUES ('XERM','Exercise Room');
