CREATE TABLE IF NOT EXISTS alberta_skill_codes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    skill_code VARCHAR(4),
    description VARCHAR(60),
    CONSTRAINT uiq_skillcode_description UNIQUE (skill_code, description)
);
INSERT IGNORE INTO alberta_skill_codes VALUES (1,'ADCS','Addictions Counsellor');
INSERT IGNORE INTO alberta_skill_codes VALUES (2,'ANES','Anesthesiology');
INSERT IGNORE INTO alberta_skill_codes VALUES (3,'ANPA','Anatomical Pathology');
INSERT IGNORE INTO alberta_skill_codes VALUES (4,'ARTH','Dental Arthroscopic Certification');
INSERT IGNORE INTO alberta_skill_codes VALUES (5,'ASED','Asthma Educator');
INSERT IGNORE INTO alberta_skill_codes VALUES (6,'ATF','Active Treatment Facility');
INSERT IGNORE INTO alberta_skill_codes VALUES (7,'ATMJ','Arthroscopic TMJ Surgery');
INSERT IGNORE INTO alberta_skill_codes VALUES (8,'CAC','Computer Assessed Certification');
INSERT IGNORE INTO alberta_skill_codes VALUES (9,'CARD','Cardiology');
INSERT IGNORE INTO alberta_skill_codes VALUES (10,'CEST','Cardiac Exercise Stress Testing');
INSERT IGNORE INTO alberta_skill_codes VALUES (11,'CHIR','Chiropractic');
INSERT IGNORE INTO alberta_skill_codes VALUES (12,'CLCO','Clinical Coordinator');
INSERT IGNORE INTO alberta_skill_codes VALUES (13,'CLIM','Clinical Immunology & Allergy');
INSERT IGNORE INTO alberta_skill_codes VALUES (14,'CLNS','Clinic Nurse');
INSERT IGNORE INTO alberta_skill_codes VALUES (15,'CMCE','Community Medicine - Certification');
INSERT IGNORE INTO alberta_skill_codes VALUES (16,'CMSP','Community Medicine - Specialty');
INSERT IGNORE INTO alberta_skill_codes VALUES (17,'CRCM','Critical Care Medicine');
INSERT IGNORE INTO alberta_skill_codes VALUES (18,'CRSG','Cardiac Surgery');
INSERT IGNORE INTO alberta_skill_codes VALUES (19,'CTSG','Cardio & Thoracic Surgery');
INSERT IGNORE INTO alberta_skill_codes VALUES (20,'DBED','Diabetes Educator');
INSERT IGNORE INTO alberta_skill_codes VALUES (21,'DENT','General Dentistry');
INSERT IGNORE INTO alberta_skill_codes VALUES (22,'DERM','Dermatology');
INSERT IGNORE INTO alberta_skill_codes VALUES (23,'DIET','Dietician');
INSERT IGNORE INTO alberta_skill_codes VALUES (24,'DIRD','Diagnostic Radiology');
INSERT IGNORE INTO alberta_skill_codes VALUES (25,'DTUR','Dental Mechanic');
INSERT IGNORE INTO alberta_skill_codes VALUES (26,'E/M','Endocrinology/Metabolism');
INSERT IGNORE INTO alberta_skill_codes VALUES (27,'ECG','Electrocardiogram Interpretation');
INSERT IGNORE INTO alberta_skill_codes VALUES (28,'ECGC','Electrocardiogram Interpretation - Cardiology');
INSERT IGNORE INTO alberta_skill_codes VALUES (29,'ECGP','Electrocardiogram Interpretation - Pediatric');
INSERT IGNORE INTO alberta_skill_codes VALUES (30,'ECHO','Echocardiography');
INSERT IGNORE INTO alberta_skill_codes VALUES (31,'EDCO','Education Coordinator');
INSERT IGNORE INTO alberta_skill_codes VALUES (32,'EEGN','Electroencephalography - Neurosurgery');
INSERT IGNORE INTO alberta_skill_codes VALUES (33,'EEGP','Electroencephalography - Pediatrics');
INSERT IGNORE INTO alberta_skill_codes VALUES (34,'EEGR','Electroencephalography - Neurology');
INSERT IGNORE INTO alberta_skill_codes VALUES (35,'EEGY','Electroencephalography - Psychiatry');
INSERT IGNORE INTO alberta_skill_codes VALUES (36,'EMCE','Emergency Medicine - Certification');
INSERT IGNORE INTO alberta_skill_codes VALUES (37,'EMGH','Electromyography - Physical Medicine & Rehabilitation');
INSERT IGNORE INTO alberta_skill_codes VALUES (38,'EMGN','Electromyography - Neurosurgery');
INSERT IGNORE INTO alberta_skill_codes VALUES (39,'EMGP','Electromyography - Pediatrics');
INSERT IGNORE INTO alberta_skill_codes VALUES (40,'EMGR','Electromyography - Neurology');
INSERT IGNORE INTO alberta_skill_codes VALUES (41,'EMSP','Emergency Medicine - Specialty');
INSERT IGNORE INTO alberta_skill_codes VALUES (42,'ENDO','Endodontics');
INSERT IGNORE INTO alberta_skill_codes VALUES (43,'EVA','Evoked Response - Auditory');
INSERT IGNORE INTO alberta_skill_codes VALUES (44,'EVR','Evoked Response');
INSERT IGNORE INTO alberta_skill_codes VALUES (45,'EVS','Evoked Response - Somatosensory');
INSERT IGNORE INTO alberta_skill_codes VALUES (46,'EVV','Evoked Response - Visual');
INSERT IGNORE INTO alberta_skill_codes VALUES (47,'EXTP','External Third Party');
INSERT IGNORE INTO alberta_skill_codes VALUES (48,'FLUR','Fluoroscopy');
INSERT IGNORE INTO alberta_skill_codes VALUES (49,'FMTH','Family Therapist');
INSERT IGNORE INTO alberta_skill_codes VALUES (50,'FTER','Full Time Emergency Room Physician');
INSERT IGNORE INTO alberta_skill_codes VALUES (51,'GAST','Gastroenterology');
INSERT IGNORE INTO alberta_skill_codes VALUES (52,'GEMD','Geriatric Medicine');
INSERT IGNORE INTO alberta_skill_codes VALUES (53,'GNMH','Generalists Mental Health Physicians');
INSERT IGNORE INTO alberta_skill_codes VALUES (54,'GNSG','General Surgery');
INSERT IGNORE INTO alberta_skill_codes VALUES (55,'GP','General Practice');
INSERT IGNORE INTO alberta_skill_codes VALUES (56,'HADM','Health Administrator (APP Program)');
INSERT IGNORE INTO alberta_skill_codes VALUES (57,'HCNS','Home Care Nurse');
INSERT IGNORE INTO alberta_skill_codes VALUES (58,'HEM','Hematology');
INSERT IGNORE INTO alberta_skill_codes VALUES (59,'HEPA','Hematological Pathology');
INSERT IGNORE INTO alberta_skill_codes VALUES (60,'HLNS','Health Nurse');
INSERT IGNORE INTO alberta_skill_codes VALUES (61,'HLPN','Home License Practical Nurse');
INSERT IGNORE INTO alberta_skill_codes VALUES (62,'IDIS','Infectious Diseases');
INSERT IGNORE INTO alberta_skill_codes VALUES (63,'IMCE','Internal Medicine Certification');
INSERT IGNORE INTO alberta_skill_codes VALUES (64,'IMPL','Impedance Plethysmography');
INSERT IGNORE INTO alberta_skill_codes VALUES (65,'INMD','Internal Medicine');
INSERT IGNORE INTO alberta_skill_codes VALUES (66,'LMEY','Limited Eye Examination (GP)');
INSERT IGNORE INTO alberta_skill_codes VALUES (67,'LVC','Low Vision Certification');
INSERT IGNORE INTO alberta_skill_codes VALUES (68,'MDBI','Medical Biochemistry');
INSERT IGNORE INTO alberta_skill_codes VALUES (69,'MDGN','Medical Genetics');
INSERT IGNORE INTO alberta_skill_codes VALUES (70,'MDMI','Medical Microbiology');
INSERT IGNORE INTO alberta_skill_codes VALUES (71,'MDON','Medical Oncology');
INSERT IGNORE INTO alberta_skill_codes VALUES (72,'MDWF','Midwife');
INSERT IGNORE INTO alberta_skill_codes VALUES (73,'MHWK','Mental Health Worker');
INSERT IGNORE INTO alberta_skill_codes VALUES (74,'MOHS','Moh\'s Microscopic Surgery');
INSERT IGNORE INTO alberta_skill_codes VALUES (75,'NCMD','Nuclear Medicine');
INSERT IGNORE INTO alberta_skill_codes VALUES (76,'NEOP','Neuro Opthamology');
INSERT IGNORE INTO alberta_skill_codes VALUES (77,'NEOT','Neuro-otology');
INSERT IGNORE INTO alberta_skill_codes VALUES (78,'NEPH','Nephrology');
INSERT IGNORE INTO alberta_skill_codes VALUES (79,'NEUR','Neurology');
INSERT IGNORE INTO alberta_skill_codes VALUES (80,'NPM','Neonatal Perinatal Medicine');
INSERT IGNORE INTO alberta_skill_codes VALUES (81,'NRPR','Nurse Practitioner');
INSERT IGNORE INTO alberta_skill_codes VALUES (82,'NUPA','Neuropathology');
INSERT IGNORE INTO alberta_skill_codes VALUES (83,'NUSG','Neurosurgery');
INSERT IGNORE INTO alberta_skill_codes VALUES (84,'OBGY','Obstetrics & Gynaecology');
INSERT IGNORE INTO alberta_skill_codes VALUES (85,'OCMD','Occupational Medicine');
INSERT IGNORE INTO alberta_skill_codes VALUES (86,'OCTH','Occupational Therapist');
INSERT IGNORE INTO alberta_skill_codes VALUES (87,'OCUL','Ocular Ultrasonography');
INSERT IGNORE INTO alberta_skill_codes VALUES (88,'OPHT','Ophthalmology');
INSERT IGNORE INTO alberta_skill_codes VALUES (89,'OPTC','Optician');
INSERT IGNORE INTO alberta_skill_codes VALUES (90,'OPTO','Optometry');
INSERT IGNORE INTO alberta_skill_codes VALUES (91,'ORPA','Oral Pathology');
INSERT IGNORE INTO alberta_skill_codes VALUES (92,'ORRD','Oral Radiology');
INSERT IGNORE INTO alberta_skill_codes VALUES (93,'ORSG','Oral Maxillofacial Surgery');
INSERT IGNORE INTO alberta_skill_codes VALUES (94,'ORTD','Orthodontics');
INSERT IGNORE INTO alberta_skill_codes VALUES (95,'ORTH','Orthopaedic Surgery');
INSERT IGNORE INTO alberta_skill_codes VALUES (96,'OTOL','Otolaryngology');
INSERT IGNORE INTO alberta_skill_codes VALUES (97,'OVAC','Oculo-visual Assessment Certification');
INSERT IGNORE INTO alberta_skill_codes VALUES (98,'PATH','General Pathology');
INSERT IGNORE INTO alberta_skill_codes VALUES (99,'PBNS','Public Health Nurse');
INSERT IGNORE INTO alberta_skill_codes VALUES (100,'PDGE','Pediatric Gastroenterology');
INSERT IGNORE INTO alberta_skill_codes VALUES (101,'PDNR','Pediatric Neurology');
INSERT IGNORE INTO alberta_skill_codes VALUES (102,'PDSG','Pediatric General Surgery');
INSERT IGNORE INTO alberta_skill_codes VALUES (103,'PED','Pediatrics');
INSERT IGNORE INTO alberta_skill_codes VALUES (104,'PEDC','Pediatric Cardiology');
INSERT IGNORE INTO alberta_skill_codes VALUES (105,'PEDN','Pediatric Nephrology');
INSERT IGNORE INTO alberta_skill_codes VALUES (106,'PEDO','Pedodontics');
INSERT IGNORE INTO alberta_skill_codes VALUES (107,'PERI','Periodontics');
INSERT IGNORE INTO alberta_skill_codes VALUES (108,'PHMC','Pharmacist');
INSERT IGNORE INTO alberta_skill_codes VALUES (109,'PHMD','Physical Medicine and Rehabilitation');
INSERT IGNORE INTO alberta_skill_codes VALUES (110,'PHTA','Physio Therapy Assistant (B)');
INSERT IGNORE INTO alberta_skill_codes VALUES (111,'PHTH','Physio Therapy');
INSERT IGNORE INTO alberta_skill_codes VALUES (112,'PHYS','Physical Therapy');
INSERT IGNORE INTO alberta_skill_codes VALUES (113,'PLAS','Plastic Surgery');
INSERT IGNORE INTO alberta_skill_codes VALUES (114,'PMCN','Primary Care Nurse');
INSERT IGNORE INTO alberta_skill_codes VALUES (115,'POD','Podiatry');
INSERT IGNORE INTO alberta_skill_codes VALUES (116,'PODS','Podiatric Surgery');
INSERT IGNORE INTO alberta_skill_codes VALUES (117,'PROS','Prosthodontics');
INSERT IGNORE INTO alberta_skill_codes VALUES (118,'PSCE','Psychiatry - Certification');
INSERT IGNORE INTO alberta_skill_codes VALUES (119,'PSCH','Psychologist');
INSERT IGNORE INTO alberta_skill_codes VALUES (120,'PSNR','Registered Psychiatric Nurse');
INSERT IGNORE INTO alberta_skill_codes VALUES (121,'PSYC','Psychiatry - Specialty');
INSERT IGNORE INTO alberta_skill_codes VALUES (122,'PUL2','Pulmonary Function - Level 2');
INSERT IGNORE INTO alberta_skill_codes VALUES (123,'PUL3','Pulmonary Function - Level 3');
INSERT IGNORE INTO alberta_skill_codes VALUES (124,'PUL4','Pulmonary Functional Level 4');
INSERT IGNORE INTO alberta_skill_codes VALUES (125,'RCTH','Recreational Therapist');
INSERT IGNORE INTO alberta_skill_codes VALUES (126,'RENL','Renal Scans');
INSERT IGNORE INTO alberta_skill_codes VALUES (127,'RHEU','Rheumatology');
INSERT IGNORE INTO alberta_skill_codes VALUES (128,'RN','Registered Nurse');
INSERT IGNORE INTO alberta_skill_codes VALUES (129,'ROCE','Radiation Oncology - Certification');
INSERT IGNORE INTO alberta_skill_codes VALUES (130,'ROSP','Radiation Oncology - Specialty');
INSERT IGNORE INTO alberta_skill_codes VALUES (131,'RSMD','Respiratory Medicine');
INSERT IGNORE INTO alberta_skill_codes VALUES (132,'RSTH','Respiratory Therapist');
INSERT IGNORE INTO alberta_skill_codes VALUES (133,'SCWK','Social Worker');
INSERT IGNORE INTO alberta_skill_codes VALUES (134,'SLPT','Speech Language Pathologist');
INSERT IGNORE INTO alberta_skill_codes VALUES (135,'SPMH','Specialists Mental Health Physicians');
INSERT IGNORE INTO alberta_skill_codes VALUES (136,'THOR','Thoracic Surgery');
INSERT IGNORE INTO alberta_skill_codes VALUES (137,'TPAC','Ther. Pharm. agents/Foreign body/Glaucoma co-management');
INSERT IGNORE INTO alberta_skill_codes VALUES (138,'TPMD','Tropical Medicine');
INSERT IGNORE INTO alberta_skill_codes VALUES (139,'ULTG','Ultrasound - Obstetrics/Gynecology');
INSERT IGNORE INTO alberta_skill_codes VALUES (140,'ULTO','Ultrasound - Opthamology');
INSERT IGNORE INTO alberta_skill_codes VALUES (141,'ULTR','Ultrasound - FULL');
INSERT IGNORE INTO alberta_skill_codes VALUES (142,'ULTU','Ultrasound - Urology');
INSERT IGNORE INTO alberta_skill_codes VALUES (143,'ULTV','Ultrasound - Vascular');
INSERT IGNORE INTO alberta_skill_codes VALUES (144,'UROL','Urology');
INSERT IGNORE INTO alberta_skill_codes VALUES (145,'VISU','Visual Fields');
INSERT IGNORE INTO alberta_skill_codes VALUES (146,'VSSG','Vascular Surgery');
INSERT IGNORE INTO alberta_skill_codes VALUES (147,'EVP','Evoked Potential');
INSERT IGNORE INTO alberta_skill_codes VALUES (148,'AUDI','Audiology');
