
export enum LinkStatus
{
	NO_LINK = "NO_LINK",
	PATIENT_REJECTED = "PATIENT_REJECTED",
	CLINIC_REJECTED = "CLINIC_REJECTED",
	PENDING_CLINIC_CONFIRM = "PENDING_CLINIC_CONFIRM",
	PENDING_PATIENT_CONFIRM = "PENDING_PATIENT_CONFIRM",
	CONFIRMED = "CONFIRMED",
	VERIFIED = "VERIFIED",
}