ALTER TABLE consultationRequests ROW_FORMAT = Dynamic;
ALTER TABLE consultationResponse ROW_FORMAT = Dynamic;
ALTER TABLE EyeformConsultationReport ROW_FORMAT = Dynamic;
ALTER TABLE professionalSpecialists ROW_FORMAT = Dynamic;

ALTER TABLE formAR ENGINE = MyISAM;
ALTER TABLE formAdf ENGINE = MyISAM;
ALTER TABLE formAdfV2 ENGINE = MyISAM;
ALTER TABLE formAlpha ENGINE = MyISAM;
ALTER TABLE formAnnualV2 ENGINE = MyISAM;
ALTER TABLE formDischargeSummary ENGINE = MyISAM;
ALTER TABLE formIntakeHx ENGINE = MyISAM;
ALTER TABLE formONAR ENGINE = MyISAM;
ALTER TABLE formONAREnhancedRecord ENGINE = MyISAM;
ALTER TABLE formONAREnhancedRecordExt1 ENGINE = MyISAM;
ALTER TABLE formONAREnhancedRecordExt2 ENGINE = MyISAM;
ALTER TABLE formPalliativeCare ENGINE = MyISAM;
ALTER TABLE formPeriMenopausal ENGINE = MyISAM;
ALTER TABLE formPositionHazard ENGINE = MyISAM;
ALTER TABLE formRhImmuneGlobulin ENGINE = MyISAM;
ALTER TABLE formRourke ENGINE = MyISAM;
ALTER TABLE formRourke2006 ENGINE = MyISAM;
ALTER TABLE formSF36 ENGINE = MyISAM;
ALTER TABLE formSF36Caregiver ENGINE = MyISAM;
ALTER TABLE formSelfAssessment ENGINE = MyISAM;
ALTER TABLE formType2Diabetes ENGINE = MyISAM;
ALTER TABLE formVTForm ENGINE = MyISAM;
ALTER TABLE formfollowup ENGINE = MyISAM;
ALTER TABLE formovulation ENGINE = MyISAM;
ALTER TABLE formreceptionassessment ENGINE = MyISAM;



